version: "3.4"
services:
  # APP
  districtr:
    build:
      context: app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    profiles:
      - app
      
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db