version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  db:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db