import * as aws from "@pulumi/aws";
import {config} from "./config";
import {Alb} from "./alb";
import {Database} from "./database";
import {ClusterResources} from "./cluster";
import {Backend} from "./backend";
import {Frontend} from "./frontend";

export function createMonitoring(
  alb: Alb,
  database: Database,
  clusterResources: ClusterResources,
  backend: Backend,
  frontend: Frontend
) {
  const name = config.name;

  const topic = new aws.sns.Topic(`${name}-alarms`, {name: `${name}-alarms`});

  if (config.alarmEmail) {
    new aws.sns.TopicSubscription(`${name}-alarms-email`, {
      topic: topic.arn,
      protocol: "email",
      endpoint: config.alarmEmail,
    });
  }

  const alarmDefaults = {
    alarmActions: [topic.arn],
    okActions: [topic.arn],
    treatMissingData: "notBreaching",
  };

  new aws.cloudwatch.MetricAlarm(`${name}-alb-5xx`, {
    ...alarmDefaults,
    name: `${name}-alb-target-5xx`,
    namespace: "AWS/ApplicationELB",
    metricName: "HTTPCode_Target_5XX_Count",
    dimensions: {LoadBalancer: alb.alb.arnSuffix},
    statistic: "Sum",
    period: 300,
    evaluationPeriods: 1,
    threshold: 25,
    comparisonOperator: "GreaterThanThreshold",
    alarmDescription: "Backend/frontend targets returning 5xx",
  });

  // 502/503/504 generated by the ALB itself (no healthy targets, keep-alive
  // races, timeouts) never hit a target and are invisible to the alarm above.
  new aws.cloudwatch.MetricAlarm(`${name}-alb-elb-5xx`, {
    ...alarmDefaults,
    name: `${name}-alb-elb-5xx`,
    namespace: "AWS/ApplicationELB",
    metricName: "HTTPCode_ELB_5XX_Count",
    dimensions: {LoadBalancer: alb.alb.arnSuffix},
    statistic: "Sum",
    period: 300,
    evaluationPeriods: 1,
    threshold: 10,
    comparisonOperator: "GreaterThanThreshold",
    alarmDescription: "ALB-generated 5xx (no healthy targets / timeouts)",
  });

  for (const [label, targetGroup] of [
    ["backend", alb.backendTargetGroup],
    ["frontend", alb.frontendTargetGroup],
  ] as const) {
    new aws.cloudwatch.MetricAlarm(`${name}-${label}-unhealthy`, {
      ...alarmDefaults,
      name: `${name}-${label}-unhealthy-targets`,
      namespace: "AWS/ApplicationELB",
      metricName: "UnHealthyHostCount",
      dimensions: {
        LoadBalancer: alb.alb.arnSuffix,
        TargetGroup: targetGroup.arnSuffix,
      },
      statistic: "Maximum",
      period: 60,
      evaluationPeriods: 3,
      threshold: 0,
      comparisonOperator: "GreaterThanThreshold",
      alarmDescription: `${label} target group has unhealthy targets`,
    });
  }

  for (const [label, service] of [
    ["backend", backend.service],
    ["frontend", frontend.service],
  ] as const) {
    // The backend's in-RAM graph cache is the main OOM risk.
    new aws.cloudwatch.MetricAlarm(`${name}-${label}-memory`, {
      ...alarmDefaults,
      name: `${name}-${label}-memory-high`,
      namespace: "AWS/ECS",
      metricName: "MemoryUtilization",
      dimensions: {
        ClusterName: clusterResources.cluster.name,
        ServiceName: service.name,
      },
      statistic: "Average",
      period: 300,
      evaluationPeriods: 2,
      threshold: 85,
      comparisonOperator: "GreaterThanThreshold",
      alarmDescription: `${label} service memory above 85%`,
    });
  }

  new aws.cloudwatch.MetricAlarm(`${name}-db-cpu`, {
    ...alarmDefaults,
    name: `${name}-db-cpu-high`,
    namespace: "AWS/RDS",
    metricName: "CPUUtilization",
    dimensions: {DBInstanceIdentifier: database.db.identifier},
    statistic: "Average",
    period: 300,
    evaluationPeriods: 2,
    threshold: 80,
    comparisonOperator: "GreaterThanThreshold",
    alarmDescription: "RDS CPU above 80%",
  });

  new aws.cloudwatch.MetricAlarm(`${name}-db-storage`, {
    ...alarmDefaults,
    name: `${name}-db-storage-low`,
    namespace: "AWS/RDS",
    metricName: "FreeStorageSpace",
    dimensions: {DBInstanceIdentifier: database.db.identifier},
    statistic: "Minimum",
    period: 300,
    evaluationPeriods: 1,
    threshold: 10 * 1024 * 1024 * 1024,
    comparisonOperator: "LessThanThreshold",
    alarmDescription: "RDS free storage below 10GB",
  });

  return {topic};
}
