"""
Tests for partisan evaluation metrics, validated against gerrychain / gerrytools.

The hardcoded fixtures and expected values in this file were generated by
the snippets below, run in a venv with `gerrytools==1.2.1` installed
(gerrytools requires Python 3.12 and pulls in gerrychain), with
PYTHONHASHSEED=0 set for reproducibility:

    PYTHONHASHSEED=0 python regen_script.py

Re-run if the metric implementations change in a way that requires
regenerating reference values.

----------------------------------------------------------------------------
Suite 1 — seed=42, 8 districts, no spatial structure
  (_DISTRICT_STATS, _EXPECTED_*)
----------------------------------------------------------------------------

  import random
  import gerrychain.metrics.partisan as gp
  from gerrychain import Election
  from gerrychain.updaters.election import ElectionResults
  from gerrychain.graph import Graph
  from gerrychain import Partition
  import networkx as nx
  from gerrytools.scoring.partisan import (
      _party_districts, _swing_districts, _competitive_contests,
  )

  random.seed(42)
  ELECTIONS = ["pres_2016", "pres_2020", "pres_2024",
               "sen_2016", "sen_2018", "sen_2020", "sen_2022"]

  districts = {}
  for d in range(1, 9):
      row = {}
      for elec in ELECTIONS:
          total = random.randint(8000, 12000)
          dem = random.randint(int(total * 0.3), int(total * 0.7))
          row[f"{elec}_dem"] = dem
          row[f"{elec}_rep"] = total - dem
      districts[d] = row

  # Per-election ElectionResults (no graph needed for partisan-bias / EG / MM)
  def make_results(name):
      election = Election(name, {"Democratic": f"{name}_dem", "Republican": f"{name}_rep"})
      counts = {p: {z: districts[z][f"{name}_{p_short}"] for z in districts}
                for p, p_short in [("Democratic", "dem"), ("Republican", "rep")]}
      return ElectionResults(election, counts, list(districts.keys()))
  results = {e: make_results(e) for e in ELECTIONS}
  # gp.efficiency_gap(r), gp.mean_median(r), gp.partisan_bias(r),
  # r.seats("Democratic"), r.percent("Democratic")  # used for proportionality

  # competitive metrics need a Partition; build a trivial chain graph with one
  # node per district so part.parts.keys() == [1..8].
  g = nx.path_graph(8)
  for n in range(8): g.nodes[n].update(districts[n + 1])
  updaters = {e: Election(e, {"Democratic": f"{e}_dem", "Republican": f"{e}_rep"}) for e in ELECTIONS}
  part = Partition(Graph.from_networkx(g), {n: n + 1 for n in range(8)}, updaters=updaters)
  # _party_districts(part, ELECTIONS, "Democratic"|"Republican")
  # _swing_districts(part, ELECTIONS, "Democratic")
  # _competitive_contests(part, ELECTIONS, "Democratic", points_within=0.03)
"""

import math
from datetime import datetime, timezone
import sqlalchemy
import sqlmodel
from unittest.mock import MagicMock

import pytest
from hypothesis import given, settings, assume
from hypothesis import strategies as st

from app.evaluation.context import DocumentEvaluationContext, GerrydbTableName, COUNTY_CONTEXT, CountyContext
from app.evaluation.models import CountyDemographics
from tests.conftest import PARENT_GRID_NAME, _GRID_BLOCK_ROWS, _GRID_ELEC_COLS
from app.evaluation.partisans import (
    competitive_metrics,
    eguia_county,
    efficiency_gap,
    mean_median,
    partisan_bias,
    disproportionality,
    seats,
    votes,
    vote_shares,
)
from app.models import DistrictUnionsResponse, DistrictrMap


class _StubEvaluationContext(DocumentEvaluationContext):
    """Test double that injects district_stats directly, bypassing the DB.

    Writes to the cached_property's slot on first access so the descriptor
    never fires, freeing tests from needing a real session or background_tasks.
    """

    def __init__(self, district_stats: list[DistrictUnionsResponse]):
        super().__init__(
            background_tasks=None,  # type: ignore[arg-type]
            session=None,  # type: ignore[arg-type]
            document_id="stub",
        )
        # Pre-populate the cached_property by writing to instance __dict__,
        # so the descriptor never fires and never tries to hit the DB.
        self.district_stats = district_stats


# ---------------------------------------------------------------------------
# 8-district, 7-election fixture (seed=42, generated via gerrychain reference)
# ---------------------------------------------------------------------------

_now = datetime.now(timezone.utc)

_DISTRICT_STATS = [
    DistrictUnionsResponse(zone=1, geometry=None, demographic_data={'total_pop_20': 10000, 'pres_2016_dem': 4097, 'pres_2016_rep': 6522, 'pres_2020_dem': 5467, 'pres_2020_rep': 2635, 'pres_2024_dem': 3740, 'pres_2024_rep': 5386, 'sen_2016_dem': 3245, 'sen_2016_rep': 5669, 'sen_2018_dem': 4143, 'sen_2018_rep': 6873, 'sen_2020_dem': 3943, 'sen_2020_rep': 6828, 'sen_2022_dem': 6581, 'sen_2022_rep': 3837}, updated_at=_now),
    DistrictUnionsResponse(zone=2, geometry=None, demographic_data={'total_pop_20': 10000, 'pres_2016_dem': 2561, 'pres_2016_rep': 5569, 'pres_2020_dem': 3409, 'pres_2020_rep': 4974, 'pres_2024_dem': 4754, 'pres_2024_rep': 4198, 'sen_2016_dem': 3356, 'sen_2016_rep': 7109, 'sen_2018_dem': 4717, 'sen_2018_rep': 5581, 'sen_2020_dem': 6715, 'sen_2020_rep': 4217, 'sen_2022_dem': 4509, 'sen_2022_rep': 4393}, updated_at=_now),
    DistrictUnionsResponse(zone=3, geometry=None, demographic_data={'total_pop_20': 10000, 'pres_2016_dem': 5401, 'pres_2016_rep': 5012, 'pres_2020_dem': 3447, 'pres_2020_rep': 7868, 'pres_2024_dem': 4639, 'pres_2024_rep': 6469, 'sen_2016_dem': 6719, 'sen_2016_rep': 4140, 'sen_2018_dem': 3955, 'sen_2018_rep': 5438, 'sen_2020_dem': 3471, 'sen_2020_rep': 5165, 'sen_2022_dem': 6333, 'sen_2022_rep': 5587}, updated_at=_now),
    DistrictUnionsResponse(zone=4, geometry=None, demographic_data={'total_pop_20': 10000, 'pres_2016_dem': 2904, 'pres_2016_rep': 5514, 'pres_2020_dem': 3262, 'pres_2020_rep': 6294, 'pres_2024_dem': 6312, 'pres_2024_rep': 3158, 'sen_2016_dem': 5294, 'sen_2016_rep': 4114, 'sen_2018_dem': 6029, 'sen_2018_rep': 3054, 'sen_2020_dem': 5441, 'sen_2020_rep': 2736, 'sen_2022_dem': 5160, 'sen_2022_rep': 4721}, updated_at=_now),
    DistrictUnionsResponse(zone=5, geometry=None, demographic_data={'total_pop_20': 10000, 'pres_2016_dem': 4103, 'pres_2016_rep': 4408, 'pres_2020_dem': 4757, 'pres_2020_rep': 3565, 'pres_2024_dem': 6157, 'pres_2024_rep': 3043, 'sen_2016_dem': 6134, 'sen_2016_rep': 4440, 'sen_2018_dem': 4684, 'sen_2018_rep': 5680, 'sen_2020_dem': 3834, 'sen_2020_rep': 7051, 'sen_2022_dem': 5164, 'sen_2022_rep': 3023}, updated_at=_now),
    DistrictUnionsResponse(zone=6, geometry=None, demographic_data={'total_pop_20': 10000, 'pres_2016_dem': 5845, 'pres_2016_rep': 3088, 'pres_2020_dem': 3081, 'pres_2020_rep': 6104, 'pres_2024_dem': 5357, 'pres_2024_rep': 6146, 'sen_2016_dem': 4291, 'sen_2016_rep': 7258, 'sen_2018_dem': 4004, 'sen_2018_rep': 5552, 'sen_2020_dem': 5560, 'sen_2020_rep': 4297, 'sen_2022_dem': 6412, 'sen_2022_rep': 5004}, updated_at=_now),
    DistrictUnionsResponse(zone=7, geometry=None, demographic_data={'total_pop_20': 10000, 'pres_2016_dem': 4115, 'pres_2016_rep': 4551, 'pres_2020_dem': 3694, 'pres_2020_rep': 5761, 'pres_2024_dem': 5410, 'pres_2024_rep': 5335, 'sen_2016_dem': 3846, 'sen_2016_rep': 7028, 'sen_2018_dem': 4549, 'sen_2018_rep': 5946, 'sen_2020_dem': 6042, 'sen_2020_rep': 4145, 'sen_2022_dem': 3369, 'sen_2022_rep': 5633}, updated_at=_now),
    DistrictUnionsResponse(zone=8, geometry=None, demographic_data={'total_pop_20': 10000, 'pres_2016_dem': 4521, 'pres_2016_rep': 5372, 'pres_2020_dem': 5352, 'pres_2020_rep': 3753, 'pres_2024_dem': 5044, 'pres_2024_rep': 5774, 'sen_2016_dem': 5897, 'sen_2016_rep': 4907, 'sen_2018_dem': 3893, 'sen_2018_rep': 7559, 'sen_2020_dem': 6047, 'sen_2020_rep': 2891, 'sen_2022_dem': 3731, 'sen_2022_rep': 4400}, updated_at=_now),
]

_EXPECTED_EFFICIENCY_GAP = {
    "pres_2016": -0.1489474471005531,
    "pres_2020": -0.03674597878049113,
    "pres_2024": -0.049405600454758905,
    "sen_2016": 0.06956511318561483,
    "sen_2018": -0.2699339921868303,
    "sen_2020": 0.06606024265465726,
    "sen_2022": 0.22012150481010057,
}

_EXPECTED_MEAN_MEDIAN = {
    "pres_2016": 0.011828363199443859,
    "pres_2020": -0.05294812449239761,
    "pres_2024": -0.03133991919594281,
    "sen_2016": -0.005985362530381788,
    "sen_2018": -0.018161519480762223,
    "sen_2020": 0.04938689665103946,
    "sen_2022": -0.00040335852722683807,
}

_EXPECTED_PARTISAN_BIAS = {
    "pres_2016": 0.125,
    "pres_2020": -0.125,
    "pres_2024": -0.125,
    "sen_2016": 0.0,
    "sen_2018": -0.125,
    "sen_2020": 0.125,
    "sen_2022": 0.0,
}

_EXPECTED_SEATS = {
    "pres_2016": {"dem": 2, "rep": 6, "total": 8},
    "pres_2020": {"dem": 3, "rep": 5, "total": 8},
    "pres_2024": {"dem": 4, "rep": 4, "total": 8},
    "sen_2016": {"dem": 4, "rep": 4, "total": 8},
    "sen_2018": {"dem": 1, "rep": 7, "total": 8},
    "sen_2020": {"dem": 5, "rep": 3, "total": 8},
    "sen_2022": {"dem": 6, "rep": 2, "total": 8},
}

_EXPECTED_VOTES = {
    "pres_2016": {"dem": 33547, "rep": 40036, "total": 73583},
    "pres_2020": {"dem": 32469, "rep": 40954, "total": 73423},
    "pres_2024": {"dem": 41413, "rep": 39509, "total": 80922},
    "sen_2016": {"dem": 38782, "rep": 44665, "total": 83447},
    "sen_2018": {"dem": 35974, "rep": 45683, "total": 81657},
    "sen_2020": {"dem": 41053, "rep": 37330, "total": 78383},
    "sen_2022": {"dem": 41259, "rep": 36598, "total": 77857},
}

_EXPECTED_PROPORTIONALITY = {
    "pres_2016": -0.20590693502575325,
    "pres_2020": -0.0672183784372744,
    "pres_2024": -0.011764415115790516,
    "sen_2016": 0.03524991911033348,
    "sen_2018": -0.3155501059309061,
    "sen_2020": 0.10125122794483499,
    "sen_2022": 0.22006691755397711,
}

_EXPECTED_COMPETITIVENESS = {
    "n_dem_districts": 0,
    "n_rep_districts": 0,
    "n_swing_districts": 8,
    "n_competitive_districts": 6,
    "n_districts": 8,
    "n_elections": 7,
}


# ---------------------------------------------------------------------------
# Fixture-based tests against gerrychain reference values
# ---------------------------------------------------------------------------

@pytest.fixture
def grid_context():
    return _StubEvaluationContext(_DISTRICT_STATS)


def test_seats_matches_gerrychain(grid_context):
    result = seats(grid_context)
    for col, expected in _EXPECTED_SEATS.items():
        assert result[col] == expected, f"{col}: {result[col]} != {expected}"

def test_votes_matches_gerrychain(grid_context):
    result = votes(grid_context)
    for col, expected in _EXPECTED_VOTES.items():
        assert result[col] == expected, f"{col}: {result[col]} != {expected}"

def test_efficiency_gap_matches_gerrychain(grid_context):
    result = efficiency_gap(grid_context)
    for col, expected in _EXPECTED_EFFICIENCY_GAP.items():
        assert result[col] == pytest.approx(expected), f"{col}"


def test_mean_median_matches_gerrychain(grid_context):
    result = mean_median(grid_context)
    for col, expected in _EXPECTED_MEAN_MEDIAN.items():
        assert result[col] == pytest.approx(expected), f"{col}"


def test_partisan_bias_matches_gerrychain(grid_context):
    result = partisan_bias(grid_context)
    for col, expected in _EXPECTED_PARTISAN_BIAS.items():
        assert result[col] == pytest.approx(expected), f"{col}"


def test_proportionality_matches_gerrychain(grid_context):
    result = disproportionality(grid_context)
    for col, expected in _EXPECTED_PROPORTIONALITY.items():
        assert result[col] == pytest.approx(expected), f"{col}"


def test_competitiveness_matches_gerrychain(grid_context):
    result = competitive_metrics(grid_context)
    for col, expected in _EXPECTED_COMPETITIVENESS.items():
        assert result[col] == expected, f"{col}: {result[col]} != {expected}"

# ---------------------------------------------------------------------------
# Grid-based partisan metric tests
# ---------------------------------------------------------------------------

def _aggregate_district_stats(block_rows: list[dict]) -> list[DistrictUnionsResponse]:
    """Aggregate block rows into per-district DistrictUnionsResponse objects.

    Zone = block_index // 8 + 1 (8 blocks per row, one district per row).
    """
    agg_cols = [*_GRID_ELEC_COLS, "total_pop_20"]
    districts: dict[int, dict] = {}
    for i, row in enumerate(block_rows):
        zone = i // 8 + 1
        if zone not in districts:
            districts[zone] = {k: 0 for k in agg_cols}
        for k in agg_cols:
            districts[zone][k] += row.get(k, 0)
    return [
        DistrictUnionsResponse(zone=z, geometry=None, demographic_data=data, updated_at=_now)
        for z, data in sorted(districts.items())
    ]


_GRID_DISTRICT_STATS = _aggregate_district_stats(_GRID_BLOCK_ROWS)

_STUB_TABLE = "test_table"

# Expected scores computed by running gerrychain/gerrytools on the data in
# fixtures/gerrydb/grid_child.csv (see generation script in conftest.py).
_GRID_EXPECTED_EGUIA = {
    "pres_2016": 0.12564661366031227,
    "pres_2020": 0.23772631478110928,
    "pres_2024": 0.23591819139764347,
    "sen_2016": 0.1321486732445637,
    "sen_2018": 0.10342226266883803,
    "sen_2020": 0.24783264680524952,
    "sen_2022": -0.14684117252610407,
}

_GRID_EXPECTED_EFFICIENCY_GAP = {
    "pres_2016": 0.18561125350181795,
    "pres_2020": 0.15713809104971035,
    "pres_2024": 0.20698488877359103,
    "sen_2016": 0.3591208658322752,
    "sen_2018": 0.1254180602006689,
    "sen_2020": 0.12207758979115362,
    "sen_2022": -0.023386589924249943,
}

_GRID_EXPECTED_MEAN_MEDIAN = {
    "pres_2016": 0.01186025265097057,
    "pres_2020": 0.0013322696352465746,
    "pres_2024": 0.00491290476478623,
    "sen_2016": -0.00427483898905745,
    "sen_2018": 0.009402174334972146,
    "sen_2020": 0.010284980633473717,
    "sen_2022": -0.00993515807140416,
}

_GRID_EXPECTED_PARTISAN_BIAS = {
    "pres_2016": 0.125,
    "pres_2020": 0.125,
    "pres_2024": 0.0,
    "sen_2016": 0.0,
    "sen_2018": 0.125,
    "sen_2020": 0.125,
    "sen_2022": 0.0,
}

_GRID_EXPECTED_SEATS = {
    "pres_2016": {"dem": 6, "rep": 2, "total": 8},
    "pres_2020": {"dem": 5, "rep": 3, "total": 8},
    "pres_2024": {"dem": 6, "rep": 2, "total": 8},
    "sen_2016": {"dem": 7, "rep": 1, "total": 8},
    "sen_2018": {"dem": 5, "rep": 3, "total": 8},
    "sen_2020": {"dem": 5, "rep": 3, "total": 8},
    "sen_2022": {"dem": 4, "rep": 4, "total": 8},
}

_GRID_EXPECTED_VOTES = {
    "pres_2016": {"dem": 17363, "rep": 16191, "total": 33554},
    "pres_2020": {"dem": 16670, "rep": 16301, "total": 32971},
    "pres_2024": {"dem": 15488, "rep": 15350, "total": 30838},
    "sen_2016": {"dem": 17103, "rep": 15975, "total": 33078},
    "sen_2018": {"dem": 16524, "rep": 16366, "total": 32890},
    "sen_2020": {"dem": 15531, "rep": 15736, "total": 31267},
    "sen_2022": {"dem": 15331, "rep": 14900, "total": 30231},
}

_GRID_EXPECTED_PROPORTIONALITY = {
    "pres_2016": 0.23253561423377245,
    "pres_2020": 0.11940417336447184,
    "pres_2024": 0.24776250081068807,
    "sen_2016": 0.3579493923453655,
    "sen_2018": 0.1225980541197933,
    "sen_2020": 0.12827821665014233,
    "sen_2022": -0.007128444312129889,
}

_GRID_EXPECTED_COMPETITIVENESS = {
    "n_dem_districts": 0,
    "n_rep_districts": 0,
    "n_swing_districts": 8,
    "n_competitive_districts": 29,
    "n_districts": 8,
    "n_elections": 7
}

@pytest.fixture
def grid_district_context():
    return _StubEvaluationContext(_GRID_DISTRICT_STATS)


@pytest.fixture
def eguia_context(session, grid_shatterable_districtr_map):
    """Exercises the full Eguia path with a real DB session (no mocks).

    Data sourced from _GRID_BLOCK_ROWS / _GRID_VTD_ROWS in conftest.py.
    """
    COUNTY_CONTEXT._cache.pop(PARENT_GRID_NAME, None)
    COUNTY_CONTEXT._attempts.pop(PARENT_GRID_NAME, None)

    grid_map = session.exec(
        sqlmodel.select(DistrictrMap).where(
            DistrictrMap.districtr_map_slug == "grid_shatterable"
        )
    ).one()

    ctx = _StubEvaluationContext(_GRID_DISTRICT_STATS)
    ctx.session = session
    ctx._districtr_map = grid_map
    yield ctx

    COUNTY_CONTEXT._cache.pop(PARENT_GRID_NAME, None)
    COUNTY_CONTEXT._attempts.pop(PARENT_GRID_NAME, None)


def test_grid_seats_matches_gerrychain(grid_district_context):
    result = seats(grid_district_context)
    for col, expected in _GRID_EXPECTED_SEATS.items():
        assert result[col] == expected, f"{col}: {result[col]} != {expected}"

def test_grid_votes_matches_gerrychain(grid_district_context):
    result = votes(grid_district_context)
    for col, expected in _GRID_EXPECTED_VOTES.items():
        assert result[col] == expected, f"{col}: {result[col]} != {expected}"

def test_grid_efficiency_gap_matches_gerrychain(grid_district_context):
    result = efficiency_gap(grid_district_context)
    for col, expected in _GRID_EXPECTED_EFFICIENCY_GAP.items():
        assert result[col] == pytest.approx(expected), f"{col}"


def test_grid_mean_median_matches_gerrychain(grid_district_context):
    result = mean_median(grid_district_context)
    for col, expected in _GRID_EXPECTED_MEAN_MEDIAN.items():
        assert result[col] == pytest.approx(expected), f"{col}"


def test_grid_partisan_bias_matches_gerrychain(grid_district_context):
    result = partisan_bias(grid_district_context)
    for col, expected in _GRID_EXPECTED_PARTISAN_BIAS.items():
        assert result[col] == pytest.approx(expected), f"{col}"


def test_grid_proportionality_matches_gerrychain(grid_district_context):
    result = disproportionality(grid_district_context)
    for col, expected in _GRID_EXPECTED_PROPORTIONALITY.items():
        assert result[col] == pytest.approx(expected), f"{col}"


def test_grid_eguia_matches_gerrychain(eguia_context):
    result = eguia_county(eguia_context)
    for col, expected in _GRID_EXPECTED_EGUIA.items():
        assert result[col] == pytest.approx(expected), f"{col}"


def test_context_parent_layer_raises_when_not_configured():
    """context.parent_layer raises ValueError when the districtr map has no parent_layer."""
    ctx = _StubEvaluationContext(_GRID_DISTRICT_STATS)
    mock_map = MagicMock()
    mock_map.parent_layer = None
    ctx.__dict__["_districtr_map"] = mock_map
    with pytest.raises(ValueError):
        _ = ctx.parent_layer


def test_eguia_raises_once_attempts_exhausted():
    """eguia() raises ValueError once MAX_LOAD_ATTEMPTS is reached without a successful
    ideal computation (e.g. malformed gerrydb table missing total_pop_20)."""
    ctx = _StubEvaluationContext(_GRID_DISTRICT_STATS)
    ctx.parent_layer = GerrydbTableName(_STUB_TABLE)

    COUNTY_CONTEXT._attempts[_STUB_TABLE] = CountyContext.MAX_LOAD_ATTEMPTS
    try:
        with pytest.raises(ValueError):
            eguia_county(ctx)
    finally:
        COUNTY_CONTEXT._attempts.pop(_STUB_TABLE, None)


def test_ideals_for_eguia_retries_then_gives_up():
    """Failures are retried up to MAX_LOAD_ATTEMPTS times; subsequent calls
    raise immediately without hitting the DB."""
    table = GerrydbTableName(_STUB_TABLE)
    singleton = CountyContext()
    singleton._ensure_county_data = MagicMock()
    singleton._compute_ideal = MagicMock(side_effect=ValueError("no data"))

    for attempt in range(1, CountyContext.MAX_LOAD_ATTEMPTS + 1):
        with pytest.raises(ValueError):
            singleton.ideals_for_eguia(table, MagicMock())
        assert singleton._compute_ideal.call_count == attempt

    # After exhausting attempts, raises without additional DB work.
    with pytest.raises(ValueError, match="failed to load after"):
        singleton.ideals_for_eguia(table, MagicMock())
    assert singleton._compute_ideal.call_count == CountyContext.MAX_LOAD_ATTEMPTS


def test_ideals_for_eguia_recovers_after_transient_failure():
    """A transient failure on one attempt doesn't block a later successful
    attempt; once recovered, the result is permanently cached and _compute_ideal
    is never called again."""
    table = GerrydbTableName(_STUB_TABLE)
    good_ideals = {"pres_2020_dem": 0.6, "pres_2020_rep": 0.4}
    singleton = CountyContext()
    singleton._ensure_county_data = MagicMock()
    singleton._compute_ideal = MagicMock(side_effect=[ValueError("transient"), good_ideals])

    with pytest.raises(ValueError):
        singleton.ideals_for_eguia(table, MagicMock())
    assert singleton._attempts[table] == 1

    assert singleton.ideals_for_eguia(table, MagicMock()) == good_ideals
    assert singleton._cache[table] == good_ideals

    # All further calls hit the cache — _compute_ideal is not called again.
    assert singleton.ideals_for_eguia(table, MagicMock()) == good_ideals
    assert singleton._compute_ideal.call_count == 2


def test_ensure_county_data_calls_populate_when_no_valid_rows():
    """_ensure_county_data triggers _populate_county_data when no row with
    non-null total_pop exists (covers both the no-rows and null-total_pop cases)."""
    table = GerrydbTableName(_STUB_TABLE)
    singleton = CountyContext()
    singleton._populate_county_data = MagicMock()

    mock_session = MagicMock()
    mock_session.exec.return_value.first.return_value = None

    singleton._ensure_county_data(table, mock_session)

    singleton._populate_county_data.assert_called_once_with(table, mock_session)


def test_ensure_county_data_skips_populate_when_valid_rows_exist():
    """_ensure_county_data is a no-op when a row with non-null total_pop exists."""
    table = GerrydbTableName(_STUB_TABLE)
    singleton = CountyContext()
    singleton._populate_county_data = MagicMock()

    mock_session = MagicMock()
    mock_session.exec.return_value.first.return_value = MagicMock()

    singleton._ensure_county_data(table, mock_session)

    singleton._populate_county_data.assert_not_called()


def test_grid_competitiveness_matches_gerrychain(grid_district_context):
    result = competitive_metrics(grid_district_context)
    for col, expected in _GRID_EXPECTED_COMPETITIVENESS.items():
        assert result[col] == expected, f"{col}: {result[col]} != {expected}"


# ---------------------------------------------------------------------------
# Retesting for a past bug: eguia county aggregation must use parent_layer (VTD base
# table), not the shatterable UNION ALL materialized view.
# ---------------------------------------------------------------------------

def test_populate_county_data_rejects_materialized_view(
    session, gerrydb_ks_ellis_geos_view
):
    """_populate_county_data must raise for materialized views.

    The shatterable gerrydb view (ks_ellis_geos) is a UNION ALL of VTD and
    block rows. Inserting from it would double-count every county.
    The pg_class.relkind guard must raise rather than silently skip.
    """
    shatterable_view = GerrydbTableName("ks_ellis_geos")

    with pytest.raises(ValueError, match="plain table"):
        CountyContext()._populate_county_data(shatterable_view, session)


def test_eguia_uses_parent_layer_not_shatterable_view(
    session, gerrydb_ks_ellis_geos_view, ks_ellis_shatterable_districtr_map
):
    """Regression: county_demographics must be keyed by parent_layer (VTD base
    table), never by the shatterable UNION ALL view. Aggregating the view would
    double-count every county because both VTD and block rows resolve to the
    same 5-char county GEOID."""
    parent_layer = GerrydbTableName("ks_ellis_county_vtd")
    shatterable_view = GerrydbTableName("ks_ellis_geos")

    for key in [parent_layer, shatterable_view]:
        COUNTY_CONTEXT._cache.pop(key, None)
        COUNTY_CONTEXT._attempts.pop(key, None)

    try:
        ks_map = session.exec(
            sqlmodel.select(DistrictrMap).where(
                DistrictrMap.gerrydb_table_name == "ks_ellis_geos"
            )
        ).one()

        ctx = _StubEvaluationContext([
            DistrictUnionsResponse(
                zone=1, geometry=None,
                demographic_data={"pres_20_dem": 100, "pres_20_rep": 200},
                updated_at=_now,
            )
        ])
        ctx.session = session
        ctx._districtr_map = ks_map

        try:
            eguia_county(ctx)
        except ValueError:
            pass  # Computation may fail if county data lacks election columns; side effects are what matter.

        parent_rows = session.exec(
            sqlmodel.select(CountyDemographics).where(
                CountyDemographics.gerrydb_table_name == parent_layer
            )
        ).all()
        assert len(parent_rows) > 0, (
            "county_demographics must be populated from parent_layer (VTD base table)"
        )

        view_rows = session.exec(
            sqlmodel.select(CountyDemographics).where(
                CountyDemographics.gerrydb_table_name == shatterable_view
            )
        ).all()
        assert len(view_rows) == 0, (
            "county_demographics must not be populated from a materialized view"
        )
    finally:
        for key in [parent_layer, shatterable_view]:
            COUNTY_CONTEXT._cache.pop(key, None)
            COUNTY_CONTEXT._attempts.pop(key, None)


# ---------------------------------------------------------------------------
# Zero-total-votes error tests
# ---------------------------------------------------------------------------

_ZERO_VOTE_STATS = [
    DistrictUnionsResponse(
        zone=1, geometry=None,
        demographic_data={"total_pop_20": 1000, "pres_2020_dem": 0, "pres_2020_rep": 0},
        updated_at=_now,
    )
]


def test_efficiency_gap_raises_on_zero_total_votes():
    ctx = _StubEvaluationContext(_ZERO_VOTE_STATS)
    with pytest.raises(ZeroDivisionError):
        efficiency_gap(ctx)


def test_vote_shares_raises_on_zero_total_votes():
    ctx = _StubEvaluationContext(_ZERO_VOTE_STATS)
    with pytest.raises(ZeroDivisionError):
        vote_shares(ctx)


def test_disproportionality_raises_on_zero_total_votes():
    ctx = _StubEvaluationContext(_ZERO_VOTE_STATS)
    with pytest.raises(ZeroDivisionError):
        disproportionality(ctx)


# ---------------------------------------------------------------------------
# Fuzz tests — property-based, via Hypothesis
#
# Strategy: generate random vote distributions (min=0, including all-zero) and
# assert mathematical invariants that must hold for any valid input, including
# half-baked plans where some or all districts have no votes. Metrics return
# float("nan") when a result is undefined (zero-vote denominator).
# ---------------------------------------------------------------------------

_FUZZ_ELECTIONS = [
    "pres_2016", "pres_2020", "pres_2024",
    "sen_2016", "sen_2018", "sen_2020", "sen_2022",
]


@st.composite
def _partisan_district_stats(draw):
    n = draw(st.integers(min_value=1, max_value=20))
    districts = []
    for zone in range(1, n + 1):
        data = {"total_pop_20": draw(st.integers(min_value=1, max_value=1000000))}
        for e in _FUZZ_ELECTIONS:
            data[f"{e}_dem"] = draw(st.integers(min_value=0, max_value=50000))
            data[f"{e}_rep"] = draw(st.integers(min_value=0, max_value=50000))
        districts.append(
            DistrictUnionsResponse(zone=zone, geometry=None, demographic_data=data, updated_at=_now)
        )
    return districts


@given(_partisan_district_stats())
@settings(max_examples=100)
def test_fuzz_seats_invariants(district_stats):
    ctx = _StubEvaluationContext(district_stats)
    result = seats(ctx)
    n = len(district_stats)
    for col, counts in result.items():
        assert counts["dem"] >= 0, f"{col}: dem seats negative"
        assert counts["rep"] >= 0, f"{col}: rep seats negative"
        # ties count for neither party, so sum may be less than n
        assert counts["dem"] + counts["rep"] <= n, f"{col}: seat sum exceeds n_districts"


@given(_partisan_district_stats())
@settings(max_examples=100)
def test_fuzz_efficiency_gap_invariants(district_stats):
    ctx = _StubEvaluationContext(district_stats)
    assume(all(ctx.total_state_votes[e] > 0 for e in ctx.elections))
    result = efficiency_gap(ctx)
    assert set(result.keys()) == set(_FUZZ_ELECTIONS)
    for col, val in result.items():
        assert -1.0 <= val <= 1.0, f"{col}: EG {val} outside [-1, 1]"


@given(_partisan_district_stats())
@settings(max_examples=100)
def test_fuzz_mean_median_invariants(district_stats):
    ctx = _StubEvaluationContext(district_stats)
    result = mean_median(ctx)
    assert set(result.keys()) == set(_FUZZ_ELECTIONS)
    for col, val in result.items():
        # nan when every district's total votes are zero (empty series after filtering)
        assert math.isnan(val) or (-0.5 <= val <= 0.5), f"{col}: mean-median {val} outside [-0.5, 0.5]"


@given(_partisan_district_stats())
@settings(max_examples=100)
def test_fuzz_partisan_bias_invariants(district_stats):
    ctx = _StubEvaluationContext(district_stats)
    result = partisan_bias(ctx)
    n = len(district_stats)
    assert set(result.keys()) == set(_FUZZ_ELECTIONS)
    for col, val in result.items():
        assert -0.5 <= val <= 0.5, f"{col}: partisan bias {val} outside [-0.5, 0.5]"
        # bias = (dem_seats - n/2) / n, so val * 2n is always an integer
        assert (val * 2 * n) == pytest.approx(round(val * 2 * n), abs=1e-9), (
            f"{col}: {val} is not a multiple of 1/(2*{n})"
        )


@given(_partisan_district_stats())
@settings(max_examples=100)
def test_fuzz_disproportionality_invariants(district_stats):
    ctx = _StubEvaluationContext(district_stats)
    assume(all(ctx.total_state_votes[e] > 0 for e in ctx.elections))
    result = disproportionality(ctx)
    assert set(result.keys()) == set(_FUZZ_ELECTIONS)
    for col, val in result.items():
        assert -1.0 <= val <= 1.0, f"{col}: disproportionality {val} outside [-1, 1]"


@given(_partisan_district_stats())
@settings(max_examples=100)
def test_fuzz_competitive_metrics_invariants(district_stats):
    ctx = _StubEvaluationContext(district_stats)
    result = competitive_metrics(ctx)
    n = len(district_stats)
    n_e = len(_FUZZ_ELECTIONS)
    assert result["n_districts"] == n
    assert result["n_elections"] == n_e
    for key in ("n_dem_districts", "n_rep_districts", "n_swing_districts", "n_competitive_districts"):
        assert result[key] >= 0, f"{key} is negative"
    # every district must be dem, rep, or swing
    assert result["n_dem_districts"] + result["n_rep_districts"] + result["n_swing_districts"] == n
    # competitive contests counted per (district, election) pair
    assert result["n_competitive_districts"] <= n * n_e
