# Generated by Django 5.2.15 on 2026-06-11 01:23

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DistrictrMap",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField()),
                ("districtr_map_slug", models.CharField(unique=True)),
                ("gerrydb_table_name", models.CharField(blank=True, null=True)),
                ("num_districts", models.IntegerField(blank=True, null=True)),
                ("num_districts_modifiable", models.BooleanField(default=True)),
                ("tiles_s3_path", models.CharField(blank=True, null=True)),
                (
                    "extent",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=None
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "map_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("local", "Local"),
                            ("community", "Community"),
                        ],
                        default="default",
                    ),
                ),
                ("comment", models.CharField(blank=True, null=True)),
                (
                    "parent_geo_unit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vtd", "VTD"),
                            ("bg", "Block group"),
                            ("block", "Block"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "child_geo_unit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vtd", "VTD"),
                            ("bg", "Block group"),
                            ("block", "Block"),
                        ],
                        null=True,
                    ),
                ),
                ("data_source_name", models.CharField(blank=True, null=True)),
                (
                    "statefps",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), blank=True, null=True, size=None
                    ),
                ),
                ("comment_length_limit", models.IntegerField(blank=True, null=True)),
                ("comment_count_limit", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Districtr map",
                "verbose_name_plural": "Districtr maps",
                "db_table": "districtrmap",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictrMapOverlays",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "map-to-overlay link",
                "verbose_name_plural": "map-to-overlay links",
                "db_table": "districtrmap_overlays",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictrMapsToGroups",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "map-to-group link",
                "verbose_name_plural": "map-to-group links",
                "db_table": "districtrmaps_to_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GerryDBTable",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GerryDB table",
                "verbose_name_plural": "GerryDB tables",
                "db_table": "gerrydbtable",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MapGroup",
            fields=[
                ("slug", models.CharField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
            ],
            options={
                "verbose_name": "map group",
                "verbose_name_plural": "map groups",
                "db_table": "map_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Overlay",
            fields=[
                (
                    "overlay_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.CharField(blank=True, null=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[("geojson", "GeoJSON"), ("pmtiles", "PMTiles")]
                    ),
                ),
                (
                    "layer_type",
                    models.CharField(
                        choices=[("fill", "Fill"), ("line", "Line"), ("text", "Text")]
                    ),
                ),
                ("custom_style", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(blank=True, null=True)),
                ("source_layer", models.CharField(blank=True, null=True)),
                ("id_property", models.CharField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "overlay",
                "managed": False,
            },
        ),
    ]
