# Use official Node.js image as the base image
FROM node:18-alpine
FROM node:18-bullseye

# Set working directory inside the container
WORKDIR /app

RUN apt-get update && apt-get install -y wget gnupg ca-certificates

# Install dependencies
RUN apt-get install -y \
  chromium \
  chromium-common \
  chromium-driver \
  fonts-liberation \
  libappindicator3-1 \
  libasound2 \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libcups2 \
  libdbus-1-3 \
  libnss3 \
  libx11-xcb1 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  xdg-utils \
  --no-install-recommends

# Copy package.json and package-lock.json to install dependencies first
COPY package.json package-lock.json ./