import {
  tomato,
  red,
  ruby,
  crimson,
  pink,
  plum,
  purple,
  violet,
  iris,
  indigo,
  blue,
  cyan,
  teal,
  jade,
  green,
  grass,
  orange,
  amber,
  yellow,
  gold,
  brown,
  bronze,
  gray,
  mint,
  lime,
  sky,
} from "@radix-ui/colors";

export const palette = {
  colors: {
    ...(tomato as object),
    ...(red as object),
    ...(ruby as object),
    ...(crimson as object),
    ...(pink as object),
    ...(plum as object),
    ...(purple as object),
    ...(violet as object),
    ...(iris as object),
    ...(indigo as object),
    ...(blue as object),
    ...(cyan as object),
    ...(teal as object),
    ...(jade as object),
    ...(green as object),
    ...(grass as object),
    ...(orange as object),
    ...(amber as object),
    ...(yellow as object),
    ...(gold as object),
    ...(brown as object),
    ...(bronze as object),
    ...(gray as object),
    ...(mint as object),
    ...(lime as object),
    ...(sky as object),
  } as { [key: string]: { [key: string]: string } },
};

// bright colors!
export const color10 = [
  tomato.tomato10,
  red.red10,
  ruby.ruby10,
  crimson.crimson10,
  pink.pink10,
  plum.plum10,
  purple.purple10,
  violet.violet10,
  iris.iris10,
  indigo.indigo10,
  blue.blue10,
  cyan.cyan10,
  teal.teal10,
  jade.jade10,
  green.green10,
  grass.grass10,
  orange.orange10,
  amber.amber10,
  yellow.yellow10,
  gold.gold10,
  brown.brown10,
  bronze.bronze10,
  gray.gray10,
  mint.mint10,
  lime.lime10,
  sky.sky10,
];
