name: vap and election batch tileset load
version: 0.1.0
tilesets:
  ak_all_vap_elec:
    - gpkg: ak_vtd_all_vap_elec.gpkg
      layer_name: ak_vtd_all_vap_elec_graph
      new_layer_name: ak_vtd_all_vap_elec
    - gpkg: ak_block_all_vap_elec.gpkg
      layer_name: ak_block_all_vap_elec_graph
      new_layer_name: ak_block_all_vap_elec
  co_all_vap_elec:
    - gpkg: co_vtd_all_vap_elec.gpkg
      layer_name: co_vtd_all_vap_elec_graph
      new_layer_name: co_vtd_all_vap_elec
    - gpkg: co_block_all_vap_elec.gpkg
      layer_name: co_block_all_vap_elec_graph
      new_layer_name: co_block_all_vap_elec
  fl_all_vap_elec:
    - gpkg: fl_vtd_all_vap_elec.gpkg
      layer_name: fl_vtd_all_vap_elec_graph
      new_layer_name: fl_vtd_all_vap_elec
    - gpkg: fl_block_all_vap_elec.gpkg
      layer_name: fl_block_all_vap_elec_graph
      new_layer_name: fl_block_all_vap_elec
  ks_all_vap_elec:
    - gpkg: ks_vtd_all_vap_elec.gpkg
      layer_name: ks_vtd_all_vap_elec_graph
      new_layer_name: ks_vtd_all_vap_elec
    - gpkg: ks_block_all_vap_elec.gpkg
      layer_name: ks_block_all_vap_elec_graph
      new_layer_name: ks_block_all_vap_elec
  ma_all_vap_elec:
    - gpkg: ma_vtd_all_vap_elec.gpkg
      layer_name: ma_vtd_all_vap_elec_graph
      new_layer_name: ma_vtd_all_vap_elec
    - gpkg: ma_block_all_vap_elec.gpkg
      layer_name: ma_block_all_vap_elec_graph
      new_layer_name: ma_block_all_vap_elec
  mt_all_vap_elec:
    - gpkg: mt_vtd_all_vap_elec.gpkg
      layer_name: mt_vtd_all_vap_elec_graph
      new_layer_name: mt_vtd_all_vap_elec
    - gpkg: mt_block_all_vap_elec.gpkg
      layer_name: mt_block_all_vap_elec_graph
      new_layer_name: mt_block_all_vap_elec
  nc_all_vap_elec:
    - gpkg: nc_vtd_all_vap_elec.gpkg
      layer_name: nc_vtd_all_vap_elec_graph
      new_layer_name: nc_vtd_all_vap_elec
    - gpkg: nc_block_all_vap_elec.gpkg
      layer_name: nc_block_all_vap_elec_graph
      new_layer_name: nc_block_all_vap_elec
  pa_all_vap_elec:
    - gpkg: pa_vtd_all_vap_elec.gpkg
      layer_name: pa_vtd_all_vap_elec_graph
      new_layer_name: pa_vtd_all_vap_elec
    - gpkg: pa_block_all_vap_elec.gpkg
      layer_name: pa_block_all_vap_elec_graph
      new_layer_name: pa_block_all_vap_elec
  tx_all_vap_elec:
    - gpkg: tx_vtd_all_vap_elec.gpkg
      layer_name: tx_vtd_all_vap_elec_graph
      new_layer_name: tx_vtd_all_vap_elec
    - gpkg: tx_block_all_vap_elec.gpkg
      layer_name: tx_block_all_vap_elec_graph
      new_layer_name: tx_block_all_vap_elec
  wa_all_vap_elec:
    - gpkg: wa_vtd_all_vap_elec.gpkg
      layer_name: wa_vtd_all_vap_elec_graph
      new_layer_name: wa_vtd_all_vap_elec
    - gpkg: wa_block_all_vap_elec.gpkg
      layer_name: wa_block_all_vap_elec_graph
      new_layer_name: wa_block_all_vap_elec
