name: vap and election batch tileset load
version: 0.1.0
tilesets:
  ak_districtr_view:
    - gpkg: ak_vtd_districtr_view.gpkg
      layer_name: ak_vtd_districtr_view
      new_layer_name: ak_vtd_districtr_view
    - gpkg: ak_block_districtr_view.gpkg
      layer_name: ak_block_districtr_view
      new_layer_name: ak_block_districtr_view
  co_districtr_view:
    - gpkg: co_vtd_districtr_view.gpkg
      layer_name: co_vtd_districtr_view
      new_layer_name: co_vtd_districtr_view
    - gpkg: co_block_districtr_view.gpkg
      layer_name: co_block_districtr_view
      new_layer_name: co_block_districtr_view
  fl_districtr_view:
    - gpkg: fl_vtd_districtr_view.gpkg
      layer_name: fl_vtd_districtr_view
      new_layer_name: fl_vtd_districtr_view
    - gpkg: fl_block_districtr_view.gpkg
      layer_name: fl_block_districtr_view
      new_layer_name: fl_block_districtr_view
  ks_districtr_view:
    - gpkg: ks_vtd_districtr_view.gpkg
      layer_name: ks_vtd_districtr_view
      new_layer_name: ks_vtd_districtr_view
    - gpkg: ks_block_districtr_view.gpkg
      layer_name: ks_block_districtr_view
      new_layer_name: ks_block_districtr_view
  ma_districtr_view:
    - gpkg: ma_vtd_districtr_view.gpkg
      layer_name: ma_vtd_districtr_view
      new_layer_name: ma_vtd_districtr_view
    - gpkg: ma_block_districtr_view.gpkg
      layer_name: ma_block_districtr_view
      new_layer_name: ma_block_districtr_view
  mt_districtr_view:
    - gpkg: mt_vtd_districtr_view.gpkg
      layer_name: mt_vtd_districtr_view
      new_layer_name: mt_vtd_districtr_view
    - gpkg: mt_block_districtr_view.gpkg
      layer_name: mt_block_districtr_view
      new_layer_name: mt_block_districtr_view
  nc_districtr_view:
    - gpkg: nc_vtd_districtr_view.gpkg
      layer_name: nc_vtd_districtr_view
      new_layer_name: nc_vtd_districtr_view
    - gpkg: nc_block_districtr_view.gpkg
      layer_name: nc_block_districtr_view
      new_layer_name: nc_block_districtr_view
  pa_districtr_view:
    - gpkg: pa_vtd_districtr_view.gpkg
      layer_name: pa_vtd_districtr_view
      new_layer_name: pa_vtd_districtr_view
    - gpkg: pa_block_districtr_view.gpkg
      layer_name: pa_block_districtr_view
      new_layer_name: pa_block_districtr_view
  tx_districtr_view:
    - gpkg: tx_vtd_districtr_view.gpkg
      layer_name: tx_vtd_districtr_view
      new_layer_name: tx_vtd_districtr_view
    - gpkg: tx_block_districtr_view.gpkg
      layer_name: tx_block_districtr_view
      new_layer_name: tx_block_districtr_view
  wa_districtr_view:
    - gpkg: wa_vtd_districtr_view.gpkg
      layer_name: wa_vtd_districtr_view
      new_layer_name: wa_vtd_districtr_view
    - gpkg: wa_block_districtr_view.gpkg
      layer_name: wa_block_districtr_view
      new_layer_name: wa_block_districtr_view
  wv_districtr_view:
    - gpkg: wv_cbg_districtr_view.gpkg
      layer_name: wv_cbg_districtr_view
      new_layer_name: wv_cbg_districtr_view
    - gpkg: wv_block_districtr_view.gpkg
      layer_name: wv_block_districtr_view
      new_layer_name: wv_block_districtr_view
