"""zone comments

Revision ID: 0db008690d60
Revises: dc7408074929
Create Date: 2025-09-19 13:38:48.680831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0db008690d60"
down_revision: Union[str, None] = "dc7408074929"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_comment",
        sa.Column("zone", sa.Integer(), nullable=True),
        schema="comments",
    )
    op.create_index(
        op.f("ix_comments_document_comment_document_id"),
        "document_comment",
        ["document_id"],
        unique=False,
        schema="comments",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_comments_document_comment_document_id"),
        table_name="document_comment",
        schema="comments",
    )
    op.drop_column("document_comment", "zone", schema="comments")
    # ### end Alembic commands ###
