"""add num_districts to document

Revision ID: 111fa461521c
Revises: 24137793FE9B
Create Date: 2026-01-26 00:00:00.000000

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa

from app.core.config import settings

# revision identifiers, used by Alembic.
revision: str = "111fa461521c"
down_revision: str | None = "24137793FE9B"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("num_districts", sa.Integer(), nullable=True),
        schema="document",
    )
    op.create_index(
        op.f("ix_document_document_num_districts"),
        "document",
        ["num_districts"],
        unique=False,
        schema="document",
    )
    op.add_column(
        "districtrmap",
        sa.Column(
            "num_districts_modifiable",
            sa.Boolean(),
            nullable=False,
            server_default="true",
        ),
    )

    # create_districtr_map is now implemented in Python (app.utils), not as a UDF.
    # Drop the old UDF overloads if present.
    op.execute(
        sa.text(
            "DROP FUNCTION IF EXISTS create_districtr_map(VARCHAR, VARCHAR, VARCHAR, "
            "INTEGER, VARCHAR, VARCHAR, VARCHAR, BOOLEAN, VARCHAR)"
        )
    )
    op.execute(
        sa.text(
            "DROP FUNCTION IF EXISTS create_districtr_map(VARCHAR, VARCHAR, VARCHAR, "
            "INTEGER, VARCHAR, VARCHAR, VARCHAR, BOOLEAN, VARCHAR, BOOLEAN)"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore previous UDF (without num_districts_modifiable)
    op.execute(
        sa.text(
            "DROP FUNCTION IF EXISTS create_districtr_map(VARCHAR, VARCHAR, VARCHAR, "
            "INTEGER, VARCHAR, VARCHAR, VARCHAR, BOOLEAN, VARCHAR, BOOLEAN)"
        )
    )
    with open(
        settings.SQL_DIR / "versions" / "af62f0e0276b" / "create_districtr_map_udf.sql",
        "r",
    ) as f:
        op.execute(sa.text(f.read()))

    op.drop_column("districtrmap", "num_districts_modifiable")
    op.drop_index(
        op.f("ix_document_document_num_districts"),
        table_name="document",
        schema="document",
    )
    op.drop_column("document", "num_districts", schema="document")
    # ### end Alembic commands ###
