"""clean up revisions 2

Revision ID: 239ca64ca70d
Revises: 545e708aeb30
Create Date: 2025-07-24 14:19:33.379235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "239ca64ca70d"
down_revision: Union[str, None] = "545e708aeb30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Strangely, at the time of writing, there were three documents in prod without a districtr_map_slug. They're from March so can be safely deleted.
    #
    #           created_at           |          updated_at           |             document_id              | gerrydb_table | color_scheme | districtr_map_slug | map_metadata
    # -------------------------------+-------------------------------+--------------------------------------+---------------+--------------+--------------------+--------------
    # 2025-03-17 14:26:35.132584+00 | 2025-03-17 14:27:31.549224+00 | cd2918f6-5744-426b-82d5-7fddece71f0b |               |              |                    |
    # 2025-03-17 16:24:59.996942+00 | 2025-03-17 16:30:24.041733+00 | 58d97267-8a75-42ba-95d8-8a789f7498ef |               |              |                    |
    # 2025-03-17 17:44:23.90127+00  | 2025-03-17 17:44:26.852692+00 | 3e157dc6-f1db-4a2d-9005-6613f349fa33 |               |              |                    |
    # (3 rows)

    # Same goes for deprecated modules
    #
    # districtr_v2_api=# select districtr_map_slug, created_at from document.document where districtr_map_slug not in (select districtr_map_slug from districtrmap) order by created_at desc limit 5;
    #   districtr_map_slug  |          created_at
    # ----------------------+-------------------------------
    #  ks_vtd_p14_view      | 2025-01-03 17:50:08.117179+00
    #  ks_vtd_p14_view_copy | 2025-01-03 17:50:06.054629+00
    #  ks_vtd_p14_view      | 2025-01-03 17:50:03.116076+00
    #  ks_vtd_p14_view      | 2025-01-03 17:37:24.292518+00
    #  ks_vtd_p14_view      | 2025-01-03 17:31:11.463313+00
    # (5 rows)

    op.execute("""
        DELETE FROM document.document
        WHERE districtr_map_slug IS NULL
        OR districtr_map_slug = ''
        OR districtr_map_slug NOT IN (
            SELECT districtr_map_slug FROM districtrmap
        );
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_places_content_districtr_map_slug",
        table_name="places_content",
        schema="cms",
    )
    op.drop_index(
        "idx_places_content_language", table_name="places_content", schema="cms"
    )
    op.drop_index("idx_places_content_slug", table_name="places_content", schema="cms")
    op.create_index(
        op.f("ix_cms_places_content_districtr_map_slugs"),
        "places_content",
        ["districtr_map_slugs"],
        unique=False,
        schema="cms",
    )
    op.create_index(
        op.f("ix_cms_places_content_language"),
        "places_content",
        ["language"],
        unique=False,
        schema="cms",
    )
    op.create_index(
        op.f("ix_cms_places_content_slug"),
        "places_content",
        ["slug"],
        unique=False,
        schema="cms",
    )
    op.create_unique_constraint(
        "places_content_id", "places_content", ["id"], schema="cms"
    )
    op.drop_index(
        "idx_tags_content_districtr_map_slug", table_name="tags_content", schema="cms"
    )
    op.drop_index("idx_tags_content_language", table_name="tags_content", schema="cms")
    op.drop_index("idx_tags_content_slug", table_name="tags_content", schema="cms")
    op.create_index(
        op.f("ix_cms_tags_content_districtr_map_slug"),
        "tags_content",
        ["districtr_map_slug"],
        unique=False,
        schema="cms",
    )
    op.create_index(
        op.f("ix_cms_tags_content_language"),
        "tags_content",
        ["language"],
        unique=False,
        schema="cms",
    )
    op.create_index(
        op.f("ix_cms_tags_content_slug"),
        "tags_content",
        ["slug"],
        unique=False,
        schema="cms",
    )
    op.create_unique_constraint("tags_content_id", "tags_content", ["id"], schema="cms")
    op.alter_column(
        "document",
        "districtr_map_slug",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=False,
        schema="document",
    )
    op.create_unique_constraint(
        "document_id_unique", "document", ["document_id"], schema="document"
    )
    op.create_foreign_key(
        "document_districtrmap_fkey",
        "document",
        "districtrmap",
        ["districtr_map_slug"],
        ["districtr_map_slug"],
        source_schema="document",
    )
    op.drop_constraint(
        "unique_document", "map_document_token", schema="document", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_document", "map_document_token", ["document_id"], schema="document"
    )
    op.drop_constraint(
        "document_districtrmap_fkey", "document", schema="document", type_="foreignkey"
    )
    op.drop_constraint(
        "document_id_unique", "document", schema="document", type_="unique"
    )
    op.alter_column(
        "document",
        "districtr_map_slug",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=True,
        schema="document",
    )
    op.drop_constraint("tags_content_id", "tags_content", schema="cms", type_="unique")
    op.drop_index(
        op.f("ix_cms_tags_content_slug"), table_name="tags_content", schema="cms"
    )
    op.drop_index(
        op.f("ix_cms_tags_content_language"), table_name="tags_content", schema="cms"
    )
    op.drop_index(
        op.f("ix_cms_tags_content_districtr_map_slug"),
        table_name="tags_content",
        schema="cms",
    )
    op.create_index(
        "idx_tags_content_slug", "tags_content", ["slug"], unique=False, schema="cms"
    )
    op.create_index(
        "idx_tags_content_language",
        "tags_content",
        ["language"],
        unique=False,
        schema="cms",
    )
    op.create_index(
        "idx_tags_content_districtr_map_slug",
        "tags_content",
        ["districtr_map_slug"],
        unique=False,
        schema="cms",
    )
    op.drop_constraint(
        "places_content_id", "places_content", schema="cms", type_="unique"
    )
    op.drop_index(
        op.f("ix_cms_places_content_slug"), table_name="places_content", schema="cms"
    )
    op.drop_index(
        op.f("ix_cms_places_content_language"),
        table_name="places_content",
        schema="cms",
    )
    op.drop_index(
        op.f("ix_cms_places_content_districtr_map_slugs"),
        table_name="places_content",
        schema="cms",
    )
    op.create_index(
        "idx_places_content_slug",
        "places_content",
        ["slug"],
        unique=False,
        schema="cms",
    )
    op.create_index(
        "idx_places_content_language",
        "places_content",
        ["language"],
        unique=False,
        schema="cms",
    )
    op.create_index(
        "idx_places_content_districtr_map_slug",
        "places_content",
        ["districtr_map_slugs"],
        unique=False,
        schema="cms",
    )
    # ### end Alembic commands ###
