"""add user session model

Revision ID: 2dbfabc0a613
Revises: dcce5c519ecc
Create Date: 2025-01-29 19:54:16.597158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models import UUIDType

# revision identifiers, used by Alembic.
revision: str = "2dbfabc0a613"
down_revision: Union[str, None] = "dcce5c519ecc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = "dcce5c519ecc"


def upgrade() -> None:
    op.create_table(
        "map_document_user_session",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("session_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("document_id", UUIDType(), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
        schema="document",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("map_document_user_session", schema="document")
    # ### end Alembic commands ###
