"""add doc token

Revision ID: 377c9e19cdfc
Revises: 39b5120b40a6
Create Date: 2025-02-09 15:55:19.667673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.models

# revision identifiers, used by Alembic.
revision: str = "377c9e19cdfc"
down_revision: Union[str, None] = "39b5120b40a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('map_document_metadata',
    # sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('metadata_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('document_id', app.models.UUIDType(), nullable=True),
    # sa.Column('map_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    # sa.PrimaryKeyConstraint('metadata_id'),
    # schema='document'
    # )
    op.create_table(
        "map_document_token",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("token_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("document_id", app.models.UUIDType(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("expiration_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("token_id"),
        sa.UniqueConstraint("document_id", name="unique_document"),
        schema="document",
    )
    # op.create_table('map_document_user_session',
    # sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.String(), nullable=False),
    # sa.Column('document_id', app.models.UUIDType(), nullable=True),
    # sa.PrimaryKeyConstraint('session_id'),
    # sa.UniqueConstraint('document_id', name='unique_document'),
    # schema='document'
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('map_document_user_session', schema='document')
    op.drop_table("map_document_token", schema="document")
    # op.drop_table('map_document_metadata', schema='document')
    # ### end Alembic commands ###
