"""comment_moderation_and_moderation

Revision ID: 38aaabc9744d
Revises: 846afa42e0cb
Create Date: 2025-08-07 16:58:29.228127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38aaabc9744d"
down_revision: Union[str, None] = "846afa42e0cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_moderation",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("moderation_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.comment.id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
        schema="comments",
    )
    op.create_index(
        op.f("ix_comments_comment_moderation_comment_id"),
        "comment_moderation",
        ["comment_id"],
        unique=True,
        schema="comments",
    )
    op.create_table(
        "commenter_moderation",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("commenter_id", sa.Integer(), nullable=False),
        sa.Column("moderation_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commenter_id"],
            ["comments.commenter.id"],
        ),
        sa.PrimaryKeyConstraint("commenter_id"),
        schema="comments",
    )
    op.create_index(
        op.f("ix_comments_commenter_moderation_commenter_id"),
        "commenter_moderation",
        ["commenter_id"],
        unique=True,
        schema="comments",
    )
    op.create_table(
        "tag_moderation",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("moderation_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["comments.tag.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id"),
        schema="comments",
    )
    op.create_index(
        op.f("ix_comments_tag_moderation_tag_id"),
        "tag_moderation",
        ["tag_id"],
        unique=True,
        schema="comments",
    )
    op.drop_index(
        "idx_commenter_first_name_and_email", table_name="commenter", schema="comments"
    )
    op.create_index(
        "idx_commenter_first_name_and_email",
        "commenter",
        [sa.text("lower(trim(first_name))"), sa.text("lower(trim(email))")],
        unique=False,
        schema="comments",
    )
    op.create_unique_constraint(
        None, "document_comment", ["comment_id"], schema="comments"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_commenter_first_name_and_email", table_name="commenter", schema="comments"
    )
    op.create_index(
        "idx_commenter_first_name_and_email",
        "commenter",
        [
            sa.text("lower(TRIM(BOTH FROM first_name))"),
            sa.text("lower(TRIM(BOTH FROM email))"),
        ],
        unique=False,
        schema="comments",
    )
    op.drop_index(
        op.f("ix_comments_tag_moderation_tag_id"),
        table_name="tag_moderation",
        schema="comments",
    )
    op.drop_table("tag_moderation", schema="comments")
    op.drop_index(
        op.f("ix_comments_commenter_moderation_commenter_id"),
        table_name="commenter_moderation",
        schema="comments",
    )
    op.drop_table("commenter_moderation", schema="comments")
    op.drop_index(
        op.f("ix_comments_comment_moderation_comment_id"),
        table_name="comment_moderation",
        schema="comments",
    )
    op.drop_table("comment_moderation", schema="comments")
    # ### end Alembic commands ###
