"""shattering models

Revision ID: 3f732ad6ce98
Revises: 8437ce954087
Create Date: 2024-09-09 08:14:02.100209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app.models


# revision identifiers, used by Alembic.
revision: str = "3f732ad6ce98"
down_revision: Union[str, None] = "8437ce954087"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "districtrmap",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("uuid", app.models.UUIDType(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "gerrydb_table_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("num_districts", sa.Integer(), nullable=True),
        sa.Column("tiles_s3_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parent_layer", app.models.UUIDType(), nullable=False),
        sa.Column("child_layer", app.models.UUIDType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_layer"],
            ["gerrydbtable.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_layer"],
            ["gerrydbtable.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "parentchildedges",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("districtr_map", app.models.UUIDType(), nullable=False),
        sa.Column("parent_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("child_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["districtr_map"],
            ["districtrmap.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("gerrydbtable", "tiles_s3_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gerrydbtable",
        sa.Column("tiles_s3_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_table("parentchildedges")
    op.drop_table("districtrmap")
    # ### end Alembic commands ###
