"""get pop totals udf

Revision ID: 48a91c29aae9
Revises: 556843a0c3bf
Create Date: 2024-07-22 22:58:33.621016

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.constants import SQL_DIR


# revision identifiers, used by Alembic.
revision: str = "48a91c29aae9"
down_revision: Union[str, None] = "556843a0c3bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gerrydbtable", "id")
    with open(f"{SQL_DIR}/total_pop_udf.sql") as f:
        query = f.read()
        op.execute(sa.text(query))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP FUNCTION IF EXISTS get_total_population"))
    op.add_column(
        "gerrydbtable",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    # ### end Alembic commands ###
