"""document and assignments tables

Revision ID: 556843a0c3bf
Revises: 966d8d72887e
Create Date: 2024-07-22 22:30:26.440565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models import UUIDType
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = "556843a0c3bf"
down_revision: Union[str, None] = "966d8d72887e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignments",
        sa.Column("document_id", UUIDType(), nullable=False),
        sa.Column("geo_id", AutoString(), nullable=False),
        sa.Column("zone", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("document_id", "geo_id"),
        sa.UniqueConstraint("document_id", "geo_id", name="document_geo_id_unique"),
        postgresql_partition_by="LIST (document_id)",
    )
    op.create_table(
        "document",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("document_id", UUIDType(), nullable=False),
        sa.Column("gerrydb_table", AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("document_id"),
        sa.UniqueConstraint("document_id"),
    )
    op.alter_column("gerrydbtable", "uuid", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("gerrydbtable", "uuid", existing_type=sa.UUID(), nullable=True)
    op.drop_table("document")
    op.drop_table("assignments")
    # ### end Alembic commands ###
