"""Add districtr map level context information

Revision ID: 55cc04197c66
Revises: 846afa42e0cb
Create Date: 2025-08-20 17:32:05.514248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55cc04197c66"
down_revision: Union[str, None] = "846afa42e0cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("districtrmap", sa.Column("comment", sa.VARCHAR(), nullable=True))
    op.add_column(
        "districtrmap", sa.Column("parent_geo_unit_type", sa.VARCHAR(), nullable=True)
    )
    op.add_column(
        "districtrmap", sa.Column("child_geo_unit_type", sa.VARCHAR(), nullable=True)
    )
    op.add_column(
        "districtrmap", sa.Column("data_source_name", sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("districtrmap", "child_geo_unit_type")
    op.drop_column("districtrmap", "parent_geo_unit_type")
    op.drop_column("districtrmap", "comment")
    op.drop_column("districtrmap", "data_source_name")
    # ### end Alembic commands ###
