"""create update metadata udf

Revision ID: 80339c4d6442
Revises: 0b0d9e1036de
Create Date: 2025-01-01 16:52:47.792773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80339c4d6442"
down_revision: Union[str, None] = "0b0d9e1036de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            CREATE OR REPLACE FUNCTION document.update_metadata(doc_id TEXT, metadata JSONB)
            RETURNS VOID AS $$
            DECLARE
                meta JSONB;
            BEGIN
                -- Loop through each k:v pair in metadata object
                FOR meta IN
                    SELECT * FROM jsonb_array_elements(metadata)
                LOOP
                    RAISE NOTICE 'Processing document_id: %', doc_id;
                    IF EXISTS (
                        SELECT 1
                        FROM document.document_metadata
                        WHERE document_metadata.document_id = doc_id
                        AND document_metadata.key = meta->>'key'
                    ) THEN
                        -- Update if exists
                        UPDATE document.document_metadata
                        SET value = meta->>'value',
                            updated_at = NOW()
                        WHERE document_metadata.document_id = doc_id
                        AND document_metadata.key = meta->>'key';
                    ELSE
                        -- Insert a new record
                        INSERT INTO document.document_metadata (document_id, key, value, created_at, updated_at)
                        VALUES (doc_id::UUID, meta->>'key', meta->>'value', NOW(), NOW());
                    END IF;
                END LOOP;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP FUNCTION document.update_metadata(document_id TEXT, metadata JSONB)"
    )
    # ### end Alembic commands ###
