"""update get_total_population udf

Revision ID: 8437ce954087
Revises: f09d9e802538
Create Date: 2024-08-16 08:36:57.326318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.constants import SQL_DIR


# revision identifiers, used by Alembic.
revision: str = "8437ce954087"
down_revision: Union[str, None] = "f09d9e802538"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with open(f"{SQL_DIR}/total_pop_udf.sql") as f:
        query = f.read()
    op.execute(sa.text(query))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("""
        CREATE OR REPLACE FUNCTION get_total_population(document_id UUID)
        RETURNS TABLE (zone TEXT, total_pop BIGINT) AS $$
        DECLARE
            gerrydb_table_name TEXT;
            sql_query TEXT;
        BEGIN
            SELECT gerrydb_table INTO gerrydb_table_name
            FROM document.document
            WHERE document.document_id = $1;
            sql_query := format('
                SELECT
                    assignments.zone::TEXT AS zone,
                    SUM(COALESCE(blocks.total_pop, 0))::BIGINT AS total_pop
                FROM document.assignments
                LEFT JOIN gerrydb.%I blocks
                ON blocks.path = assignments.geo_id
                WHERE assignments.document_id = $1
                GROUP BY assignments.zone
            ', gerrydb_table_name);
            RETURN QUERY EXECUTE sql_query USING $1;
        END;
        $$ LANGUAGE plpgsql;
    """)
    )
    # ### end Alembic commands ###
