"""document comments

Revision ID: 846afa42e0cb
Revises: 61330347d3c4
Create Date: 2025-08-06 14:37:50.469241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.models


# revision identifiers, used by Alembic.
revision: str = "846afa42e0cb"
down_revision: Union[str, None] = "61330347d3c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_comment",
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("document_id", app.core.models.UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.comment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.document.document_id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
        sa.UniqueConstraint("comment_id"),
        schema="comments",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_comment", schema="comments")
    # ### end Alembic commands ###
