"""add unique constraint on name

Revision ID: a54cdc2ba92b
Revises: 19b750d3bf2b
Create Date: 2024-08-01 00:34:35.427151

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a54cdc2ba92b"
down_revision: Union[str, None] = "19b750d3bf2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "gerrydbtiles", ["name"])
    op.create_unique_constraint(None, "gerrydbtiles", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "gerrydbtiles", type_="unique")
    op.drop_constraint(None, "gerrydbtiles", type_="unique")
    # ### end Alembic commands ###
