"""add num_districts to document

Revision ID: a1b2c3d4e5f6
Revises: 24137793FE9B
Create Date: 2026-01-26 00:00:00.000000

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "24137793FE9B"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("num_districts", sa.Integer(), nullable=True),
        schema="document",
    )
    op.create_index(
        op.f("ix_document_document_num_districts"),
        "document",
        ["num_districts"],
        unique=False,
        schema="document",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_document_num_districts"),
        table_name="document",
        schema="document",
    )
    op.drop_column("document", "num_districts", schema="document")
    # ### end Alembic commands ###
