"""add available stats to districtrmap

Revision ID: c3541f016d35
Revises: 5d9f7335f98a
Create Date: 2024-11-10 12:56:36.766141

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3541f016d35"
down_revision: Union[str, None] = "5d9f7335f98a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "districtrmap",
        sa.Column("available_summary_stats", sa.ARRAY(sa.TEXT()), nullable=True),
    )

    op.execute(
        sa.text(
            """
        UPDATE districtrmap d
        SET available_summary_stats = (
            SELECT
            CASE WHEN d.child_layer IS NOT NULL THEN
                (
                SELECT ARRAY_AGG(summary_stat) FROM get_available_summary_stats(d.child_layer)
                INTERSECT
                SELECT ARRAY_AGG(summary_stat) FROM get_available_summary_stats(d.parent_layer)
                )
            ELSE
                (SELECT ARRAY_AGG(summary_stat) FROM get_available_summary_stats(d.parent_layer))
            END
        )
    """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("districtrmap", "available_summary_stats")
    # ### end Alembic commands ###
