#!/usr/bin/env bash
# sync-skills.sh — Syncs .agents/skills/ to various AI coding agent formats.
#
# .agents/skills/ is the canonical source. This script copies/converts
# skills into the formats expected by each agent.
#
# Usage: ./sync-skills.sh [targets...] [options]
#
# Targets:
#   --claude    .claude/skills/       (Claude Code slash commands)
#   --cursor    .cursor/rules/        (Cursor AI rules)
#   --codex     codex.md              (OpenAI Codex CLI)
#   --all       All targets (default)
#
# Options:
#   --clean     Remove synced files instead of syncing
#   --help      Show this help message

set -euo pipefail

AGENTS_DIR=".agents/skills"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Extract a frontmatter field value from a SKILL.md file
get_field() {
  local file="$1" field="$2"
  sed -n '/^---$/,/^---$/p' "$file" | grep "^${field}:" | sed "s/^${field}: *//" | head -1
}

# Return everything after the closing --- of frontmatter
get_body() {
  awk 'BEGIN{n=0} /^---$/{n++; next} n>=2{print}' "$1"
}

# List all skill directories (those containing SKILL.md) under AGENTS_DIR.
# Outputs one directory path per line.
list_skill_dirs() {
  find "$AGENTS_DIR" -name SKILL.md -print0 | while IFS= read -r -d '' f; do
    dirname "$f"
  done
}

# Get the relative path of a skill directory from AGENTS_DIR.
# e.g., ".agents/skills/project/learn-backend" → "project/learn-backend"
skill_rel_path() {
  local skill_dir="$1"
  echo "${skill_dir#"$AGENTS_DIR"/}"
}

# Convert a relative path to a flat name for Cursor rule files.
# e.g., "project/learn-backend" → "project-learn-backend"
skill_flat_name() {
  echo "$1" | tr '/' '-'
}

# ---------------------------------------------------------------------------
# Claude Code — copy into .claude/skills/ preserving relative paths
# ---------------------------------------------------------------------------
sync_claude() {
  local dir=".claude/skills"
  echo "==> Claude Code (.claude/skills/)"

  # Clean and rebuild — simpler than tracking staleness across nested dirs
  if [ -d "$dir" ]; then
    rm -rf "$dir"
  fi
  mkdir -p "$dir"

  list_skill_dirs | while IFS= read -r skill; do
    [ -d "$skill" ] || continue
    local rel
    rel="$(skill_rel_path "$skill")"
    echo "  Sync: $rel"
    mkdir -p "$dir/$(dirname "$rel")"
    cp -r "$skill" "$dir/$rel"
  done
}

# ---------------------------------------------------------------------------
# Cursor — convert SKILL.md → .cursor/rules/skill-<flat-name>.mdc
#
# Cursor rules use their own frontmatter (description, globs, alwaysApply).
# Reference files are inlined so the rule is self-contained.
# Synced files are prefixed with "skill-" to avoid colliding with
# hand-written rules and to allow clean removal.
# ---------------------------------------------------------------------------
sync_cursor() {
  local dir=".cursor/rules"
  echo "==> Cursor (.cursor/rules/)"
  mkdir -p "$dir"

  # Remove all synced rules and rebuild
  for rule in "$dir"/skill-*.mdc; do
    [ -f "$rule" ] && rm -f "$rule"
  done

  list_skill_dirs | while IFS= read -r skill; do
    [ -d "$skill" ] || continue
    [ -f "$skill/SKILL.md" ] || continue
    local rel flat desc body target
    rel="$(skill_rel_path "$skill")"
    flat="$(skill_flat_name "$rel")"
    target="$dir/skill-${flat}.mdc"

    desc="$(get_field "$skill/SKILL.md" "description")"
    body="$(get_body "$skill/SKILL.md")"

    echo "  Sync: $rel"

    {
      echo "---"
      echo "description: ${desc}"
      echo "globs:"
      echo "alwaysApply: false"
      echo "---"
      echo ""
      echo "# ${rel}"
      echo ""
      echo "${body}"

      # Inline reference files so the rule is self-contained
      if [ -d "$skill/reference" ]; then
        for ref in "$skill/reference"/*.md; do
          [ -f "$ref" ] || continue
          local ref_name
          ref_name="$(basename "$ref" .md)"
          echo ""
          echo "---"
          echo ""
          echo "## Reference: ${ref_name}"
          echo ""
          cat "$ref"
        done
      fi
    } > "$target"
  done
}

# ---------------------------------------------------------------------------
# Codex — generate codex.md at repo root
#
# The OpenAI Codex CLI reads codex.md (and AGENTS.md) for project context.
# We generate an index of all skills with pointers to the canonical files
# so Codex knows what's available and where to read the full instructions.
# ---------------------------------------------------------------------------
sync_codex() {
  echo "==> Codex (codex.md)"

  {
    echo "<!-- AUTO-GENERATED by sync-skills.sh — do not edit manually -->"
    echo ""
    echo "# Codex Instructions"
    echo ""
    echo "This project has reusable agent skills in \`.agents/skills/\`."
    echo "When asked to perform one of the tasks below, read the corresponding"
    echo "SKILL.md file and follow its instructions."
    echo ""
    echo "## Available Skills"
    echo ""
    list_skill_dirs | sort | while IFS= read -r skill; do
      [ -d "$skill" ] || continue
      [ -f "$skill/SKILL.md" ] || continue
      local rel desc
      rel="$(skill_rel_path "$skill")"
      desc="$(get_field "$skill/SKILL.md" "description")"
      echo "- **${rel}** — ${desc}"
      echo "  \`.agents/skills/${rel}/SKILL.md\`"
    done
  } > codex.md

  echo "  Generated codex.md"
}

# ---------------------------------------------------------------------------
# Clean — remove all synced artifacts
# ---------------------------------------------------------------------------
clean_all() {
  echo "Cleaning synced files..."

  if [ -d ".claude/skills" ]; then
    rm -rf .claude/skills
    echo "  Removed .claude/skills/"
  fi

  local found=false
  for f in .cursor/rules/skill-*.mdc; do
    [ -f "$f" ] || continue
    rm -f "$f"
    found=true
  done
  $found && echo "  Removed .cursor/rules/skill-*.mdc"

  if [ -f "codex.md" ]; then
    rm -f codex.md
    echo "  Removed codex.md"
  fi

  echo "Done."
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if [ ! -d "$AGENTS_DIR" ]; then
  echo "Error: $AGENTS_DIR not found. Run from repo root." >&2
  exit 1
fi

targets=()
clean=false

for arg in "$@"; do
  case "$arg" in
    --claude) targets+=(claude) ;;
    --cursor) targets+=(cursor) ;;
    --codex)  targets+=(codex) ;;
    --all)    targets=(claude cursor codex) ;;
    --clean)  clean=true ;;
    --help|-h)
      sed -n '2,/^$/{ s/^# //; p }' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $arg (try --help)" >&2
      exit 1
      ;;
  esac
done

if $clean; then
  clean_all
  exit 0
fi

# Default to all targets
if [ ${#targets[@]} -eq 0 ]; then
  targets=(claude cursor codex)
fi

for target in "${targets[@]}"; do
  case "$target" in
    claude) sync_claude ;;
    cursor) sync_cursor ;;
    codex)  sync_codex ;;
  esac
done

echo ""
echo "Done. Synced to: ${targets[*]}"
