export const CANONICAL_LAYER_IDS = {
  SOURCES: {
    BLOCK: 'blocks',
    SELECTION_POINTS_PARENT: 'SELECTION_POINTS',
    SELECTION_POINTS_CHILD: 'SELECTION_POINTS_child',
    COUNTIES: 'counties',
    MAP_ORDER_ANCHORS: 'map-order-anchors',
    ZONE_LABEL: 'zone-label',
  },
  BREAKS: {
    LABELS: 'places_subplace',
  },
  MAP_ANCHORS: {
    HOVER: 'anchor-hover',
    OVERLAYS: 'anchor-overlays',
    GEOMETRY_OUTLINE: 'anchor-geometry-outline',
    DEMOGRAPHY: 'anchor-demography',
    ASSIGNMENTS: 'anchor-assignments',
    COUNTIES: 'anchor-counties',
  },
  OVERLAY: {
    SOURCE_PREFIX: 'overlay-source-',
    LAYER_PREFIX: 'overlay-layer-',
    CLICK_PREFIX: 'overlay-click-',
    SELECTED_PREFIX: 'overlay-selected-',
  },
  COUNTIES: {
    FILL: 'counties_fill',
    BOUNDARY: 'counties_boundary',
    LABELS: 'counties_labels',
  },
  BLOCK: {
    PARENT: {
      BASE: 'blocks',
      HOVER: 'blocks-hover',
      HIGHLIGHT: 'blocks-highlight',
      POINTS: 'blocks-points',
      OUTLINE: 'blocks-outline',
      BACKGROUND: 'blocks-hover-background',
    },
    CHILD: {
      BASE: 'blocks-child',
      HOVER: 'blocks-child-hover',
      HIGHLIGHT: 'blocks-highlight-child',
      POINTS: 'blocks-points-child',
      OUTLINE: 'blocks-child-outline',
      BACKGROUND: 'blocks-child-hover-background',
    },
  },
  ZONE_LABELS: {
    OUTLINE: 'ZONE_OUTLINE',
    TEXT: 'ZONE_LABEL',
    BACKGROUND: 'ZONE_LABEL_BG',
    LOCK: 'ZONE_LOCK_LABE',
  },
} as const;

// These are included here so that the migration to new constants location does not
// break things
export const BLOCK_SOURCE_ID = CANONICAL_LAYER_IDS.SOURCES.BLOCK;
export const BLOCK_LAYER_ID = CANONICAL_LAYER_IDS.BLOCK.PARENT.BASE;
export const BLOCK_LAYER_ID_CHILD = CANONICAL_LAYER_IDS.BLOCK.CHILD.BASE;
export const BLOCK_POINTS_LAYER_ID = CANONICAL_LAYER_IDS.BLOCK.PARENT.POINTS;
export const BLOCK_POINTS_LAYER_ID_CHILD = CANONICAL_LAYER_IDS.BLOCK.CHILD.POINTS;
export const BLOCK_LAYER_ID_HIGHLIGHT = CANONICAL_LAYER_IDS.BLOCK.PARENT.HIGHLIGHT;
export const BLOCK_LAYER_ID_HIGHLIGHT_CHILD = CANONICAL_LAYER_IDS.BLOCK.CHILD.HIGHLIGHT;
export const BLOCK_HOVER_LAYER_ID = CANONICAL_LAYER_IDS.BLOCK.PARENT.HOVER;
export const BLOCK_HOVER_LAYER_ID_CHILD = CANONICAL_LAYER_IDS.BLOCK.CHILD.HOVER;

export const SELECTION_POINTS_SOURCE_ID = CANONICAL_LAYER_IDS.SOURCES.SELECTION_POINTS_PARENT;
export const SELECTION_POINTS_SOURCE_ID_CHILD = CANONICAL_LAYER_IDS.SOURCES.SELECTION_POINTS_CHILD;

export const COUNTY_SOURCE_ID = CANONICAL_LAYER_IDS.SOURCES.COUNTIES;
export const COUNTY_LAYER_IDS: string[] = [
  CANONICAL_LAYER_IDS.COUNTIES.BOUNDARY,
  CANONICAL_LAYER_IDS.COUNTIES.LABELS,
] as string[];
export const COUNTY_LAYERS: string[] = [
  CANONICAL_LAYER_IDS.COUNTIES.FILL,
  CANONICAL_LAYER_IDS.COUNTIES.BOUNDARY,
  CANONICAL_LAYER_IDS.COUNTIES.LABELS,
] as string[];

export const MAP_ORDER_ANCHORS_SOURCE_ID = CANONICAL_LAYER_IDS.SOURCES.MAP_ORDER_ANCHORS;
export const MAP_LAYER_ANCHOR_IDS = {
  hover: CANONICAL_LAYER_IDS.MAP_ANCHORS.HOVER,
  overlays: CANONICAL_LAYER_IDS.MAP_ANCHORS.OVERLAYS,
  geometryOutline: CANONICAL_LAYER_IDS.MAP_ANCHORS.GEOMETRY_OUTLINE,
  demography: CANONICAL_LAYER_IDS.MAP_ANCHORS.DEMOGRAPHY,
  assignments: CANONICAL_LAYER_IDS.MAP_ANCHORS.ASSIGNMENTS,
  counties: CANONICAL_LAYER_IDS.MAP_ANCHORS.COUNTIES,
} as const;

export const LABELS_BREAK_LAYER_ID = CANONICAL_LAYER_IDS.BREAKS.LABELS;

export const ZONE_LABEL_SOURCE_ID = CANONICAL_LAYER_IDS.SOURCES.ZONE_LABEL;
export const ZONE_LABEL_LAYER_IDS = {
  OUTLINE: CANONICAL_LAYER_IDS.ZONE_LABELS.OUTLINE,
  TEXT: CANONICAL_LAYER_IDS.ZONE_LABELS.TEXT,
  BACKGROUND: CANONICAL_LAYER_IDS.ZONE_LABELS.BACKGROUND,
  LOCK: CANONICAL_LAYER_IDS.ZONE_LABELS.LOCK,
} as const;

export const GEOMETRY_OUTLINE_LAYER_IDS = {
  parent: CANONICAL_LAYER_IDS.BLOCK.PARENT.OUTLINE,
  child: CANONICAL_LAYER_IDS.BLOCK.CHILD.OUTLINE,
} as const;

export const OVERLAY_LAYER_ID_PREFIXES = {
  source: CANONICAL_LAYER_IDS.OVERLAY.SOURCE_PREFIX,
  layer: CANONICAL_LAYER_IDS.OVERLAY.LAYER_PREFIX,
  click: CANONICAL_LAYER_IDS.OVERLAY.CLICK_PREFIX,
  selected: CANONICAL_LAYER_IDS.OVERLAY.SELECTED_PREFIX,
} as const;

export const INTERACTIVE_LAYERS: string[] = [BLOCK_HOVER_LAYER_ID, BLOCK_HOVER_LAYER_ID_CHILD];
export const LINE_LAYERS = [BLOCK_LAYER_ID, BLOCK_LAYER_ID_CHILD] as const;
export const ZONE_LABEL_LAYERS: string[] = [
  ZONE_LABEL_LAYER_IDS.OUTLINE,
  ZONE_LABEL_LAYER_IDS.TEXT,
  ZONE_LABEL_LAYER_IDS.BACKGROUND,
] as string[];
export const PARENT_LAYERS: string[] = [BLOCK_LAYER_ID, BLOCK_HOVER_LAYER_ID];
export const CHILD_LAYERS: string[] = [
  BLOCK_LAYER_ID_CHILD,
  BLOCK_HOVER_LAYER_ID_CHILD,
  BLOCK_LAYER_ID_HIGHLIGHT_CHILD,
] as string[];
