import type {LayerSpecification} from 'maplibre-gl';

export const SATELLITE_BASEMAP_LAYERS: LayerSpecification[] = [
  {
    id: 'Satellite',
    type: 'raster',
    source: 'satellite',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'raster-hue-rotate': 0,
      'raster-opacity': 1,
    },
  },
  {
    id: 'Tunnel',
    type: 'line',
    source: 'maptiler_planet',
    'source-layer': 'road',
    layout: {
      'line-cap': 'butt',
      'line-join': 'miter',
      visibility: 'visible',
    },
    paint: {
      'line-color': 'hsla(0, 0%, 100%, 0.2)',
      'line-dasharray': [0.28, 0.14],
      'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 6, 0.5, 20, 30],
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      [
        'all',
        ['match', ['get', 'brunnel'], ['tunnel'], true, false],
        ['any', ['==', ['get', 'construction'], false], ['!', ['has', 'construction']]],
      ],
    ],
  },
  {
    id: 'Path',
    type: 'line',
    source: 'maptiler_planet',
    'source-layer': 'pathway',
    layout: {
      'line-cap': 'square',
      'line-join': 'bevel',
      visibility: 'visible',
    },
    paint: {
      'line-color': 'hsla(0, 0%, 97%, 0.33)',
      'line-dasharray': [1, 1],
      'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 14, 0.5, 20, 4],
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      ['match', ['get', 'brunnel'], ['bridge', 'ford'], true, ['!', ['has', 'brunnel']]],
    ],
  },
  {
    id: 'Road',
    type: 'line',
    source: 'maptiler_planet',
    'source-layer': 'road',
    minzoom: 6,
    layout: {
      'line-cap': 'butt',
      'line-join': 'round',
      visibility: 'visible',
    },
    paint: {
      'line-color': {
        stops: [
          [8, 'hsla(0, 0%, 100%, 0.2)'],
          [14, 'hsla(0, 0%, 100%, 0.4)'],
          [18, 'hsla(0, 0%, 100%, 0.5)'],
        ],
      },
      'line-width': [
        'interpolate',
        ['linear'],
        ['zoom'],
        5,
        ['match', ['get', 'class'], ['motorway', 'motorway_link'], 1, 0],
        7,
        ['match', ['get', 'class'], ['motorway', 'motorway_link', 'trunk'], 1.4, 0],
        8,
        ['match', ['get', 'class'], ['motorway', 'motorway_link', 'primary', 'trunk'], 0.75, 0],
        9,
        ['match', ['get', 'class'], ['secondary', 'tertiary'], 0.7, 1],
        10,
        ['match', ['get', 'class'], ['motorway', 'motorway_link'], 1.3, 1.3],
        14,
        ['match', ['get', 'class'], ['minor', 'service'], 0.5, 2.4],
      ],
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      ['match', ['get', 'brunnel'], ['tunnel'], false, true],
      ['any', ['==', ['get', 'construction'], false], ['!', ['has', 'construction']]],
    ],
  },
  {
    id: 'Railway',
    type: 'line',
    source: 'maptiler_planet',
    'source-layer': 'railway',
    minzoom: 11,
    layout: {
      visibility: 'visible',
    },
    paint: {
      'line-color': 'hsla(34, 0%, 100%, 0.2)',
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 11, 0.5, 16, 1.3],
      'line-width': ['interpolate', ['linear'], ['zoom'], 11, 1, 16, 2],
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      ['any', ['==', ['get', 'construction'], false], ['!', ['has', 'construction']]],
    ],
  },
  {
    id: 'Other dark border',
    type: 'line',
    source: 'maptiler_planet',
    'source-layer': 'sub_border',
    minzoom: 4,
    layout: {
      'line-cap': 'butt',
      'line-join': 'round',
      visibility: 'visible',
    },
    paint: {
      'line-color': 'hsla(0, 0%, 0%, 0.3)',
      'line-offset': 1,
      'line-opacity': [
        'step',
        ['zoom'],
        [
          'case',
          [
            'all',
            ['==', ['get', 'iso_a2'], 'FR'],
            ['match', ['get', 'admin_level'], [40], true, false],
          ],
          1,
          ['match', ['get', 'admin_level'], [50], 0, [40], 0, [30], 1, 1],
        ],
        5,
        [
          'case',
          [
            'all',
            ['==', ['get', 'iso_a2'], 'FR'],
            ['match', ['get', 'admin_level'], [40], true, false],
          ],
          1,
          ['match', ['get', 'admin_level'], [50], 0, [40], 0, [30], 1, 1],
        ],
        6,
        [
          'case',
          [
            'all',
            ['==', ['get', 'iso_a2'], 'FR'],
            ['match', ['get', 'admin_level'], [40, 50], true, false],
          ],
          1,
          ['match', ['get', 'admin_level'], [50], 0, [40], 1, [30], 1, 1],
        ],
        8,
        1,
      ],
      'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 3, 0.5, 9, 1.5, 22, 32],
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      [
        'all',
        ['any', ['==', ['get', 'maritime'], false], ['!', ['has', 'maritime']]],
        ['match', ['get', 'admin_level'], [30, 40, 50], true, false],
      ],
    ],
  },
  {
    id: 'Other border',
    type: 'line',
    source: 'maptiler_planet',
    'source-layer': 'sub_border',
    minzoom: 3,
    layout: {
      visibility: 'visible',
    },
    paint: {
      'line-color': 'hsla(0, 0%, 90%, 0.5)',
      'line-opacity': [
        'step',
        ['zoom'],
        [
          'case',
          [
            'all',
            ['==', ['get', 'iso_a2'], 'FR'],
            ['match', ['get', 'admin_level'], [40], true, false],
          ],
          1,
          ['match', ['get', 'admin_level'], [50], 0, [40], 0, [30], 1, 1],
        ],
        5,
        [
          'case',
          [
            'all',
            ['==', ['get', 'iso_a2'], 'FR'],
            ['match', ['get', 'admin_level'], [40], true, false],
          ],
          1,
          ['match', ['get', 'admin_level'], [50], 0, [40], 0, [30], 1, 1],
        ],
        6,
        [
          'case',
          [
            'all',
            ['==', ['get', 'iso_a2'], 'FR'],
            ['match', ['get', 'admin_level'], [40, 50], true, false],
          ],
          1,
          ['match', ['get', 'admin_level'], [50], 0, [40], 1, [30], 1, 1],
        ],
        8,
        1,
      ],
      'line-width': 1,
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      [
        'all',
        ['any', ['==', ['get', 'maritime'], false], ['!', ['has', 'maritime']]],
        ['match', ['get', 'admin_level'], [30, 40, 50], true, false],
      ],
    ],
  },
  {
    id: 'Country dark border',
    type: 'line',
    source: 'maptiler_planet',
    'source-layer': 'country_border',
    layout: {
      'line-cap': 'butt',
      'line-join': 'round',
      visibility: 'visible',
    },
    paint: {
      'line-color': 'hsla(0, 0%, 0%, 0.51)',
      'line-offset': 1,
      'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 3, 0.5, 9, 1.5, 22, 32],
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      ['any', ['==', ['get', 'maritime'], false], ['!', ['has', 'maritime']]],
    ],
  },
  {
    id: 'Country border',
    type: 'line',
    source: 'maptiler_planet',
    'source-layer': 'country_border',
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
      visibility: 'visible',
    },
    paint: {
      'line-color': 'hsl(0, 0%, 94%)',
      'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 3, 0.5, 9, 1.5, 22, 32],
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      ['any', ['==', ['get', 'maritime'], false], ['!', ['has', 'maritime']]],
    ],
  },
  {
    id: 'Disputed border',
    type: 'line',
    source: 'maptiler_planet',
    'source-layer': 'country_border_disputed',
    layout: {
      'line-cap': 'round',
      'line-join': 'round',
      visibility: 'visible',
    },
    paint: {
      'line-blur': 0.2,
      'line-color': 'hsl(0, 0%, 100%)',
      'line-dasharray': [2, 4],
      'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 3, 1, 9, 2.5, 22, 32],
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      ['any', ['==', ['get', 'maritime'], false], ['!', ['has', 'maritime']]],
    ],
  },
  {
    id: 'Pathway labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'pathway_label',
    minzoom: 13,
    layout: {
      'symbol-placement': 'line',
      'symbol-spacing': ['step', ['zoom'], 250, 21, 900],
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Medium'],
      'text-letter-spacing': 0.1,
      'text-rotation-alignment': 'map',
      'text-size': ['interpolate', ['linear'], ['zoom'], 10, 8, 16, 11, 22, 16],
      'text-transform': 'none',
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
  },
  {
    id: 'Road labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'road_label',
    minzoom: 11,
    layout: {
      'symbol-placement': 'line',
      'symbol-spacing': ['step', ['zoom'], 250, 21, 900],
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Medium'],
      'text-letter-spacing': 0.1,
      'text-rotation-alignment': 'map',
      'text-size': ['interpolate', ['linear'], ['zoom'], 10, 8, 16, 11, 22, 16],
      'text-transform': 'none',
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      ['any', ['==', ['get', 'construction'], false], ['!', ['has', 'construction']]],
    ],
  },
  {
    id: 'Place labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'place_label',
    minzoom: 10,
    maxzoom: 16,
    layout: {
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Regular'],
      'text-letter-spacing': 0.1,
      'text-max-width': 10,
      'text-size': ['interpolate', ['linear'], ['zoom'], 10, 12, 14, 13],
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'Point'],
      [
        'match',
        ['get', 'class'],
        ['hamlet', 'isolated_dwelling', 'neighbourhood', 'quarter', 'suburb'],
        true,
        ['!', ['has', 'class']],
      ],
    ],
  },
  {
    id: 'Village labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'place_label',
    minzoom: 10,
    maxzoom: 16,
    layout: {
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Regular'],
      'text-max-width': 10,
      'text-size': ['interpolate', ['linear'], ['zoom'], 3, 9, 6, 10, 8, 12, 10, 13],
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'Point'],
      ['match', ['get', 'class'], ['village'], true, false],
    ],
  },
  {
    id: 'Airport labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'poi_station',
    minzoom: 6,
    layout: {
      'icon-anchor': 'center',
      'icon-image': [
        'match',
        ['get', 'subclass'],
        'international',
        'airport',
        ['case', ['has', 'subclass'], 'airfield', ''],
      ],
      'icon-overlap': 'never',
      'icon-padding': 2,
      'icon-size': [
        'interpolate',
        ['linear'],
        ['zoom'],
        7,
        0.7,
        10,
        ['match', ['get', 'subclass'], 'international', 1, 0.8],
        16,
        ['match', ['get', 'subclass'], 'international', 1.2, 1],
      ],
      'text-anchor': 'top',
      'text-field': [
        'step',
        ['zoom'],
        ['coalesce', ['get', 'iata'], ['get', 'icao']],
        10,
        ['coalesce', ['get', 'iata'], ['get', 'icao']],
        13,
        ['coalesce', ['get', 'name:en'], ['get', 'name']],
      ],
      'text-font': ['Barlow Bold'],
      'text-line-height': 1.2,
      'text-max-width': 9,
      'text-offset': [0, 1],
      'text-optional': true,
      'text-overlap': 'never',
      'text-padding': 2,
      'text-size': [
        'interpolate',
        ['linear'],
        ['zoom'],
        7,
        8,
        9,
        9,
        10,
        ['match', ['get', 'subclass'], 'international', 10, 7],
        14,
        ['match', ['get', 'subclass'], 'international', 14, 12],
        18,
        ['match', ['get', 'subclass'], 'international', 18, 16],
      ],
      visibility: 'visible',
    },
    paint: {
      'icon-color': 'hsl(215, 0%, 100%)',
      'icon-halo-color': '#ffffff',
      'icon-halo-width': 2,
      'icon-opacity': [
        'step',
        ['zoom'],
        7,
        1,
        ['match', ['get', 'subclass'], ['international'], 1, 0],
        12,
        1,
      ],
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
      'text-opacity': [
        'step',
        ['zoom'],
        7,
        1,
        ['match', ['get', 'subclass'], ['international'], 1, 0],
        12,
        1,
      ],
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'Point'],
      ['match', ['get', 'class'], ['aerodrome'], true, false],
    ],
  },
  {
    id: 'Town labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'town_label',
    minzoom: 9,
    maxzoom: 16,
    layout: {
      'icon-keep-upright': true,
      'symbol-sort-key': [
        '+',
        ['case', ['==', ['get', 'capital'], 20], -1000, 0],
        ['to-number', ['get', 'rank']],
      ],
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Regular'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 3, 10, 6, 11, 8, 14, 10, 15],
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    filter: ['==', ['geometry-type'], 'Point'],
  },
  {
    id: 'State labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'state_label',
    minzoom: 3,
    maxzoom: 10,
    layout: {
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'text-anchor': 'center',
      'text-field': [
        'step',
        ['zoom'],
        ['get', 'abbrev'],
        4,
        ['coalesce', ['get', 'name:en'], ['get', 'name']],
      ],
      'text-font': ['Barlow Italic'],
      'text-letter-spacing': 0.05,
      'text-max-width': 7,
      'text-size': [
        'interpolate',
        ['linear'],
        ['zoom'],
        3,
        ['case', ['in', ['get', 'admin_level'], ['literal', [30, 40]]], 12, 8],
        7,
        [
          'case',
          ['in', ['get', 'admin_level'], ['literal', [30, 40]]],
          13,
          ['==', ['get', 'admin_level'], 50],
          12,
          12,
        ],
        9,
        [
          'case',
          ['in', ['get', 'admin_level'], ['literal', [30, 40]]],
          16,
          ['==', ['get', 'admin_level'], 50],
          13,
          14,
        ],
      ],
      'text-transform': 'uppercase',
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
      'text-opacity': [
        'step',
        ['zoom'],
        [
          'case',
          [
            'all',
            ['==', ['get', 'iso_a2'], 'FR'],
            ['match', ['get', 'admin_level'], [40], true, false],
          ],
          1,
          ['match', ['get', 'admin_level'], [50], 0, [40], 0, [30], 1, 1],
        ],
        5,
        [
          'case',
          [
            'all',
            ['==', ['get', 'iso_a2'], 'FR'],
            ['match', ['get', 'admin_level'], [40], true, false],
          ],
          1,
          ['match', ['get', 'admin_level'], [50], 0, [40], 0, [30], 1, 1],
        ],
        6,
        [
          'case',
          [
            'all',
            ['==', ['get', 'iso_a2'], 'FR'],
            ['match', ['get', 'admin_level'], [40, 50], true, false],
          ],
          1,
          ['match', ['get', 'admin_level'], [50], 0, [40], 1, [30], 1, 1],
        ],
        8,
        1,
      ],
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'Point'],
      [
        'all',
        ['match', ['get', 'admin_level'], [30, 40, 50], true, false],
        ['any', ['!', ['has', 'rank']]],
      ],
    ],
  },
  {
    id: 'City labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'city_label',
    minzoom: 3,
    maxzoom: 16,
    layout: {
      'icon-anchor': 'top',
      'icon-image': ['step', ['zoom'], 'dot', 14, ''],
      'icon-offset': [0, -2],
      'icon-size': ['interpolate', ['linear'], ['zoom'], 3, 0.4, 16, 1],
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'text-anchor': 'bottom',
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Medium'],
      'text-max-width': 10,
      'text-size': [
        'interpolate',
        ['linear', 0.5, 1, 0.5, 1],
        ['zoom'],
        4,
        11,
        6,
        13,
        8,
        16,
        12,
        18,
        16,
        20,
      ],
      visibility: 'visible',
    },
    paint: {
      'icon-color': 'hsl(0, 0%, 100%)',
      'icon-halo-color': '#ffffff',
      'icon-halo-width': 2,
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
  },
  {
    id: 'Capital city labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'city_label',
    minzoom: 3,
    maxzoom: 16,
    layout: {
      'icon-anchor': 'top',
      'icon-image': ['step', ['zoom'], 'circle-dot', 12, ''],
      'icon-offset': [0, 5],
      'icon-rotate': 0,
      'icon-size': ['interpolate', ['linear'], ['zoom'], 3, 0.5, 16, 1],
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'text-anchor': 'bottom',
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Bold'],
      'text-justify': 'center',
      'text-max-width': 10,
      'text-offset': [0, 0.5],
      'text-size': ['interpolate', ['linear'], ['zoom'], 4, 12, 6, 14, 8, 16, 12, 22, 16, 28],
      visibility: 'visible',
    },
    paint: {
      'icon-color': 'hsl(0, 0%, 100%)',
      'icon-halo-color': '#ffffff',
      'icon-halo-width': 2,
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'Point'],
      ['match', ['get', 'capital'], [20], true, false],
    ],
  },
  {
    id: 'Country labels disputed',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'country_disputed_label',
    minzoom: 3,
    maxzoom: 12,
    layout: {
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'text-field': '{name:en}',
      'text-font': ['Barlow Bold'],
      'text-max-width': 10,
      'text-size': ['interpolate', ['linear'], ['zoom'], 1, 12, 4, 14, 6, 18, 9, 22],
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    filter: [
      'all',
      ['==', ['geometry-type'], 'Point'],
      ['match', ['get', 'worldview:ch'], ['recognized'], true, ['!', ['has', 'worldview:ch']]],
    ],
  },
  {
    id: 'Country labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'country_label',
    minzoom: 1,
    maxzoom: 12,
    layout: {
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Bold'],
      'text-max-width': 10,
      'text-size': [
        'interpolate',
        ['linear', 1],
        ['zoom'],
        1,
        ['case', ['\u003C=', ['get', 'rank'], 1], 13, 12],
        4,
        ['case', ['\u003C=', ['get', 'rank'], 1], 15, 14],
        6,
        ['case', ['\u003C=', ['get', 'rank'], 1], 23, 18],
        9,
        ['case', ['\u003C=', ['get', 'rank'], 1], 27, 22],
      ],
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
  },
  {
    id: 'Continent labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'continent_label',
    minzoom: 0,
    maxzoom: 1,
    layout: {
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Bold'],
      'text-justify': 'center',
      'text-size': ['interpolate', ['exponential', 1], ['zoom'], 0, 12, 2, 14],
      'text-transform': 'uppercase',
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    metadata: {},
  },
  {
    id: 'Lake labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'water_label',
    minzoom: 5,
    layout: {
      'symbol-placement': 'line',
      'symbol-spacing': 350,
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Italic'],
      'text-letter-spacing': 0.2,
      'text-line-height': 1.2,
      'text-max-width': 10,
      'text-padding': 2,
      'text-size': ['interpolate', ['linear'], ['zoom'], 3, 12, 9, 18, 14, 21],
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    metadata: {},
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      ['match', ['get', 'class'], ['lake', 'reservoir'], true, false],
    ],
  },
  {
    id: 'Ocean labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'water_centroid',
    minzoom: 2,
    layout: {
      'icon-keep-upright': true,
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Italic'],
      'text-letter-spacing': 0.2,
      'text-line-height': 1.2,
      'text-size': ['interpolate', ['linear', 1], ['zoom'], 1, 13, 3, 16, 9, 22, 14, 26],
      'text-transform': 'uppercase',
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    metadata: {},
    filter: [
      'all',
      ['==', ['geometry-type'], 'Point'],
      ['match', ['get', 'class'], ['ocean'], true, false],
    ],
  },
  {
    id: 'Strait labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'water_label',
    minzoom: 5,
    layout: {
      'symbol-placement': 'line',
      'symbol-spacing': 350,
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Italic'],
      'text-letter-spacing': 0.2,
      'text-line-height': 1.2,
      'text-max-width': 10,
      'text-size': ['interpolate', ['linear', 1], ['zoom'], 3, 12, 9, 18, 14, 24],
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    metadata: {},
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      ['match', ['get', 'class'], ['strait'], true, false],
    ],
  },
  {
    id: 'Bay labels (lines)',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'water_label',
    minzoom: 3,
    layout: {
      'symbol-placement': 'line',
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'symbol-spacing': 350,
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Italic'],
      'text-letter-spacing': 0.2,
      'text-line-height': 1.2,
      'text-max-width': 10,
      'text-size': ['interpolate', ['linear', 1], ['zoom'], 3, 12, 9, 18, 14, 24],
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
      'text-opacity': ['step', ['zoom'], 0, 1, ['match', ['get', 'class'], ['ocean'], 1, 0], 3, 1],
    },
    metadata: {},
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      [
        'all',
        ['match', ['get', 'class'], ['bay'], true, false],
        ['match', ['get', 'worldview:ch'], ['recognized'], true, ['!', ['has', 'worldview:ch']]],
        [
          'match',
          ['get', 'name'],
          [
            'Bay of Bengal',
            'Golfe de Gascogne/Golfo de Vizcaya/Bay of Biscay',
            'Golfo de México',
            'Great Australian Bight',
            'Gulf of America',
            'Gulf of Guinea',
            'Hudson Bay',
          ],
          false,
          true,
        ],
      ],
    ],
  },
  {
    id: 'Bay labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'water_centroid',
    minzoom: 5,
    layout: {
      'icon-keep-upright': true,
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Italic'],
      'text-letter-spacing': 0.2,
      'text-line-height': 1.2,
      'text-size': ['interpolate', ['linear', 1], ['zoom'], 3, 12, 9, 18, 14, 24],
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
    },
    metadata: {},
    filter: [
      'all',
      ['==', ['geometry-type'], 'Point'],
      [
        'all',
        ['match', ['get', 'worldview:ch'], ['recognized'], true, ['!', ['has', 'worldview:ch']]],
        ['match', ['get', 'class'], ['bay'], true, false],
        [
          'match',
          ['get', 'name'],
          [
            'Bay of Bengal',
            'Golfe de Gascogne/Golfo de Vizcaya/Bay of Biscay',
            'Golfo de México',
            'Great Australian Bight',
            'Gulf of America',
            'Gulf of Guinea',
            'Hudson Bay',
          ],
          true,
          false,
        ],
      ],
    ],
  },
  {
    id: 'places_subplace',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'place_label',
    layout: {
      visibility: 'none',
    },
  },
  {
    id: 'Sea labels',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'water_centroid',
    minzoom: 3,
    layout: {
      'icon-keep-upright': true,
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Italic'],
      'text-letter-spacing': 0.2,
      'text-line-height': 1.2,
      'text-max-width': 6,
      'text-size': [
        'interpolate',
        ['linear', 1],
        ['zoom'],
        1,
        10,
        3,
        12,
        4,
        ['case', ['==', ['get', 'rank'], 1], 14, 12],
        9,
        20,
        14,
        24,
      ],
      'text-transform': 'uppercase',
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
      'text-opacity': [
        'step',
        ['zoom'],
        0,
        3,
        ['case', ['==', ['get', 'rank'], 1], 1, 0],
        4,
        ['case', ['\u003C=', ['get', 'rank'], 3], 1, 0],
        5,
        1,
      ],
    },
    metadata: {},
    filter: [
      'all',
      ['==', ['geometry-type'], 'Point'],
      [
        'all',
        ['match', ['get', 'worldview:ch'], ['recognized'], true, ['!', ['has', 'worldview:ch']]],
        [
          'match',
          ['get', 'name:en'],
          ['Adriatic Sea', 'Balearic Sea', 'Baltic Sea', 'Red Sea'],
          false,
          true,
        ],
        ['match', ['get', 'class'], ['sea'], true, false],
      ],
    ],
  },
  {
    id: 'Sea labels (lines)',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'water_label',
    minzoom: 3,
    layout: {
      'icon-keep-upright': true,
      'symbol-placement': 'line-center',
      'symbol-sort-key': ['to-number', ['get', 'rank']],
      'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
      'text-font': ['Barlow Italic'],
      'text-letter-spacing': 0.2,
      'text-line-height': 1.2,
      'text-size': [
        'interpolate',
        ['linear', 1],
        ['zoom'],
        1,
        10,
        3,
        12,
        4,
        ['case', ['==', ['get', 'rank'], 1], 14, 12],
        9,
        20,
        14,
        24,
      ],
      'text-transform': 'uppercase',
      visibility: 'visible',
    },
    paint: {
      'text-color': '#ffffff',
      'text-halo-color': '#ffffff',
      'text-halo-width': 2,
      'text-opacity': [
        'step',
        ['zoom'],
        0,
        3,
        ['case', ['==', ['get', 'rank'], 1], 1, 0],
        4,
        ['case', ['\u003C=', ['get', 'rank'], 3], 1, 0],
        5,
        1,
      ],
    },
    metadata: {},
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      [
        'all',
        ['match', ['get', 'worldview:ch'], ['recognized'], true, ['!', ['has', 'worldview:ch']]],
        ['match', ['get', 'class'], ['sea'], true, false],
        [
          'match',
          ['get', 'name:en'],
          ['Adriatic Sea', 'Balearic Sea', 'Baltic Sea', 'Red Sea'],
          true,
          false,
        ],
      ],
    ],
  },
];
