name: Fly Deploy Districtr V2 API
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/fly-deploy-api.yml"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-api
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
