name: Fly Deploy Districtr V2 App
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/fly-deploy-app.yml"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_FE_API_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
