name: Fly Deploy Districtr V2 App
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/fly-deploy-app.yml"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-app
    steps:
      - uses: actions/checkout@v3
      - name: Write .env.production
        run: |
          cat <<EOF > .env.production
            NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.RECAPTCHA_SITE_KEY }}
            NEXT_PUBLIC_S3_BUCKET_URL=https://tilesets1.cdn.districtr.org
            NEXT_PUBLIC_S3_BUCKET_URL_MIRROR1=https://tilesets2.cdn.districtr.org
            NEXT_PUBLIC_S3_BUCKET_URL_MIRROR2=https://tilesets3.cdn.districtr.org
            NEXT_PUBLIC_API_URL=https://districtr-v2-api.fly.dev
            EOF
        working-directory: app
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_FE_API_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
