name: Test backend

# on:
#   push:
#     paths:
#       - "backend/**"
#       - ".github/workflows/test-backend.yml"

on: workflow_dispatch

jobs:
  container-job:
    runs-on: ubuntu-latest

    container: python:3.12

    services:
      postgres:
        image: postgres:16.3-alpine3.20
        env:
          POSTGRES_SCHEME: postgresql+psycopg
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_SERVER: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir
        working-directory: backend

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true
        working-directory: backend

      - name: Run migrations and test
        run: alembic upgrade head && ./test.sh
        working-directory: backend
        env:
          POSTGRES_SCHEME: postgresql+psycopg
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_SERVER: postgres
          POSTGRES_PORT: 5432
          ENVIRONMENT: test
