# Generated by Django 5.2.15 on 2026-06-11 01:47

import content.blocks
import django.contrib.postgres.fields
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('boilerplate', 2), ('section_header', 4), ('plan_gallery', 12), ('comment_gallery', 18), ('form', 22), ('map_create_buttons', 26)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'underline', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'image', 'embed'], 'label': 'Rich text'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'underline', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'image', 'embed'], 'help_text': 'Optional extra prose appended to the boilerplate.', 'label': 'Custom content', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('customContent', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 3)]], {}), 5: ('wagtail.blocks.IntegerBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'Restrict the gallery to these plan IDs (empty = no filter).', 'label': 'Plan IDs'}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Restrict the gallery to plans with these tags (empty = no filter).'}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 12}), 12: ('wagtail.blocks.StructBlock', [[('ids', 6), ('tags', 8), ('title', 3), ('description', 9), ('paginate', 10), ('showListView', 10), ('showThumbnails', 10), ('showTitles', 10), ('showDescriptions', 10), ('showUpdatedAt', 10), ('showTags', 10), ('showModule', 10), ('limit', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'Restrict the gallery to these comment IDs (empty = no filter).', 'label': 'Comment IDs'}), 14: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Restrict the gallery to comments with these tags (empty = no filter).'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Zip code', 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 10}), 17: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 9), ('ids', 13), ('tags', 14), ('place', 3), ('state', 3), ('zipCode', 15), ('limit', 16), ('showIdentifier', 10), ('showTitles', 10), ('showPlaces', 10), ('showStates', 10), ('showZipCodes', 10), ('showCreatedAt', 10), ('showListView', 10), ('paginate', 10), ('showFilters', 17), ('showMaps', 10)]], {}), 19: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Tags automatically applied to every submission.', 'label': 'Mandatory tags'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': content.blocks.districtr_map_slug_choices}), 21: ('wagtail.blocks.ListBlock', (20,), {'default': [], 'help_text': 'Districtr map modules submitters may attach (empty = all).', 'label': 'Allow-listed modules'}), 22: ('wagtail.blocks.StructBlock', [[('mandatoryTags', 19), ('allowListModules', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('name', 3), ('districtr_map_slug', 20)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'default': []}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('simple', 'Simple'), ('megaphone', 'Megaphone')]}), 26: ('wagtail.blocks.StructBlock', [[('views', 24), ('type', 25)]], {})})),
                ('districtr_map_slugs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Slugs of the Districtr map modules this place page features.', size=None)),
            ],
            options={
                'verbose_name': 'place page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PlacesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'places index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TagPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('boilerplate', 2), ('section_header', 4), ('plan_gallery', 12), ('comment_gallery', 18), ('form', 22), ('map_create_buttons', 26)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'underline', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'image', 'embed'], 'label': 'Rich text'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'underline', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'image', 'embed'], 'help_text': 'Optional extra prose appended to the boilerplate.', 'label': 'Custom content', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('customContent', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 3)]], {}), 5: ('wagtail.blocks.IntegerBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'Restrict the gallery to these plan IDs (empty = no filter).', 'label': 'Plan IDs'}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Restrict the gallery to plans with these tags (empty = no filter).'}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 12}), 12: ('wagtail.blocks.StructBlock', [[('ids', 6), ('tags', 8), ('title', 3), ('description', 9), ('paginate', 10), ('showListView', 10), ('showThumbnails', 10), ('showTitles', 10), ('showDescriptions', 10), ('showUpdatedAt', 10), ('showTags', 10), ('showModule', 10), ('limit', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'Restrict the gallery to these comment IDs (empty = no filter).', 'label': 'Comment IDs'}), 14: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Restrict the gallery to comments with these tags (empty = no filter).'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Zip code', 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 10}), 17: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 9), ('ids', 13), ('tags', 14), ('place', 3), ('state', 3), ('zipCode', 15), ('limit', 16), ('showIdentifier', 10), ('showTitles', 10), ('showPlaces', 10), ('showStates', 10), ('showZipCodes', 10), ('showCreatedAt', 10), ('showListView', 10), ('paginate', 10), ('showFilters', 17), ('showMaps', 10)]], {}), 19: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Tags automatically applied to every submission.', 'label': 'Mandatory tags'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': content.blocks.districtr_map_slug_choices}), 21: ('wagtail.blocks.ListBlock', (20,), {'default': [], 'help_text': 'Districtr map modules submitters may attach (empty = all).', 'label': 'Allow-listed modules'}), 22: ('wagtail.blocks.StructBlock', [[('mandatoryTags', 19), ('allowListModules', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('name', 3), ('districtr_map_slug', 20)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'default': []}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('simple', 'Simple'), ('megaphone', 'Megaphone')]}), 26: ('wagtail.blocks.StructBlock', [[('views', 24), ('type', 25)]], {})})),
                ('districtr_map_slug', models.CharField(blank=True, default='', help_text='Slug of the Districtr map module this tag page features.', max_length=255)),
            ],
            options={
                'verbose_name': 'tag page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TagsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'tags index page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
