# Generated by Django 5.2.15 on 2026-09-23 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_alter_placepage_body_alter_staticpage_body_and_more"),
        ("content", "0004_previewsnapshot"),
    ]

    operations = []
