# Generated by Django 5.2.15 on 2026-08-06 21:25

import content.blocks
import wagtail.fields
from django.db import migrations


def fold_gallery_slugs_into_ids(apps, schema_editor):
    """Convert plan_gallery blocks that referenced a curated Gallery snippet
    (gallerySlug) into inline curated ids — the gallery's entries, in order.
    Runs while the galleries tables still exist (galleries/0004 depends on
    this migration); guarded for databases that never had them."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass('admin.galleries_gallery')")
        if cursor.fetchone()[0] is None:
            return
        cursor.execute(
            "SELECT g.slug, e.document_public_id FROM galleries_gallery g "
            "JOIN galleries_galleryentry e ON e.gallery_id = g.id "
            "ORDER BY g.slug, e.sort_order NULLS LAST, e.id"
        )
        entries_by_slug = {}
        for slug, public_id in cursor.fetchall():
            entries_by_slug.setdefault(slug, []).append(public_id)

    for model_name in ("TagPage", "PlacePage", "StaticPage"):
        model = apps.get_model("content", model_name)
        for page in model.objects.all().iterator():
            raw = page.body.raw_data if hasattr(page.body, "raw_data") else page.body
            changed = False
            for block in raw or []:
                if block.get("type") != "plan_gallery":
                    continue
                value = block.get("value") or {}
                slug = value.pop("gallerySlug", None)
                if slug is None:
                    continue
                changed = True
                if slug and not value.get("ids"):
                    value["ids"] = entries_by_slug.get(slug, [])
            if changed:
                page.body = raw
                page.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_rename_default_home_page'),
    ]

    operations = [
        migrations.RunPython(
            fold_gallery_slugs_into_ids, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='placepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('boilerplate', 2), ('section_header', 4), ('plan_gallery', 12), ('comment_gallery', 18), ('form', 22), ('map_create_buttons', 26)], blank=True, block_lookup={0: ('content.blocks.FrontendRichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'image', 'embed'], 'label': 'Rich text'}), 1: ('content.blocks.FrontendRichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'image', 'embed'], 'help_text': 'Optional extra prose appended to the boilerplate.', 'label': 'Custom content', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('customContent', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 3)]], {}), 5: ('wagtail.blocks.IntegerBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'The plans shown, in this order (empty = filter by tags instead). The review queue\'s "Add to portal gallery" appends here.', 'label': 'Curated plan IDs'}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Restrict the gallery to plans with these tags (empty = no filter).'}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 12}), 12: ('wagtail.blocks.StructBlock', [[('ids', 6), ('tags', 8), ('title', 3), ('description', 9), ('paginate', 10), ('showListView', 10), ('showThumbnails', 10), ('showTitles', 10), ('showDescriptions', 10), ('showUpdatedAt', 10), ('showTags', 10), ('showModule', 10), ('limit', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'Restrict the gallery to these comment IDs (empty = no filter).', 'label': 'Comment IDs'}), 14: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Restrict the gallery to comments with these tags (empty = no filter).'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Zip code', 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 10}), 17: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 9), ('ids', 13), ('tags', 14), ('place', 3), ('state', 3), ('zipCode', 15), ('limit', 16), ('showIdentifier', 10), ('showTitles', 10), ('showPlaces', 10), ('showStates', 10), ('showZipCodes', 10), ('showCreatedAt', 10), ('showListView', 10), ('paginate', 10), ('showFilters', 17), ('showMaps', 10)]], {}), 19: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Tags automatically applied to every submission.', 'label': 'Mandatory tags'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': content.blocks.districtr_map_slug_choices}), 21: ('wagtail.blocks.ListBlock', (20,), {'default': [], 'help_text': 'Districtr map modules submitters may attach (empty = all).', 'label': 'Allow-listed modules'}), 22: ('wagtail.blocks.StructBlock', [[('mandatoryTags', 19), ('allowListModules', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('name', 3), ('districtr_map_slug', 20)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'default': []}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('simple', 'Simple'), ('megaphone', 'Megaphone')]}), 26: ('wagtail.blocks.StructBlock', [[('views', 24), ('type', 25)]], {})}),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('boilerplate', 2), ('section_header', 4), ('plan_gallery', 12), ('comment_gallery', 18), ('form', 22), ('map_create_buttons', 26)], blank=True, block_lookup={0: ('content.blocks.FrontendRichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'image', 'embed'], 'label': 'Rich text'}), 1: ('content.blocks.FrontendRichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'image', 'embed'], 'help_text': 'Optional extra prose appended to the boilerplate.', 'label': 'Custom content', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('customContent', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 3)]], {}), 5: ('wagtail.blocks.IntegerBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'The plans shown, in this order (empty = filter by tags instead). The review queue\'s "Add to portal gallery" appends here.', 'label': 'Curated plan IDs'}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Restrict the gallery to plans with these tags (empty = no filter).'}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 12}), 12: ('wagtail.blocks.StructBlock', [[('ids', 6), ('tags', 8), ('title', 3), ('description', 9), ('paginate', 10), ('showListView', 10), ('showThumbnails', 10), ('showTitles', 10), ('showDescriptions', 10), ('showUpdatedAt', 10), ('showTags', 10), ('showModule', 10), ('limit', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'Restrict the gallery to these comment IDs (empty = no filter).', 'label': 'Comment IDs'}), 14: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Restrict the gallery to comments with these tags (empty = no filter).'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Zip code', 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 10}), 17: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 9), ('ids', 13), ('tags', 14), ('place', 3), ('state', 3), ('zipCode', 15), ('limit', 16), ('showIdentifier', 10), ('showTitles', 10), ('showPlaces', 10), ('showStates', 10), ('showZipCodes', 10), ('showCreatedAt', 10), ('showListView', 10), ('paginate', 10), ('showFilters', 17), ('showMaps', 10)]], {}), 19: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Tags automatically applied to every submission.', 'label': 'Mandatory tags'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': content.blocks.districtr_map_slug_choices}), 21: ('wagtail.blocks.ListBlock', (20,), {'default': [], 'help_text': 'Districtr map modules submitters may attach (empty = all).', 'label': 'Allow-listed modules'}), 22: ('wagtail.blocks.StructBlock', [[('mandatoryTags', 19), ('allowListModules', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('name', 3), ('districtr_map_slug', 20)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'default': []}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('simple', 'Simple'), ('megaphone', 'Megaphone')]}), 26: ('wagtail.blocks.StructBlock', [[('views', 24), ('type', 25)]], {})}),
        ),
        migrations.AlterField(
            model_name='tagpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('boilerplate', 2), ('section_header', 4), ('plan_gallery', 12), ('comment_gallery', 18), ('form', 22), ('map_create_buttons', 26)], blank=True, block_lookup={0: ('content.blocks.FrontendRichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'image', 'embed'], 'label': 'Rich text'}), 1: ('content.blocks.FrontendRichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'link', 'document-link', 'image', 'embed'], 'help_text': 'Optional extra prose appended to the boilerplate.', 'label': 'Custom content', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('customContent', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 3)]], {}), 5: ('wagtail.blocks.IntegerBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'The plans shown, in this order (empty = filter by tags instead). The review queue\'s "Add to portal gallery" appends here.', 'label': 'Curated plan IDs'}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Restrict the gallery to plans with these tags (empty = no filter).'}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 12}), 12: ('wagtail.blocks.StructBlock', [[('ids', 6), ('tags', 8), ('title', 3), ('description', 9), ('paginate', 10), ('showListView', 10), ('showThumbnails', 10), ('showTitles', 10), ('showDescriptions', 10), ('showUpdatedAt', 10), ('showTags', 10), ('showModule', 10), ('limit', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (5,), {'default': [], 'help_text': 'Restrict the gallery to these comment IDs (empty = no filter).', 'label': 'Comment IDs'}), 14: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Restrict the gallery to comments with these tags (empty = no filter).'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Zip code', 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 10}), 17: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 9), ('ids', 13), ('tags', 14), ('place', 3), ('state', 3), ('zipCode', 15), ('limit', 16), ('showIdentifier', 10), ('showTitles', 10), ('showPlaces', 10), ('showStates', 10), ('showZipCodes', 10), ('showCreatedAt', 10), ('showListView', 10), ('paginate', 10), ('showFilters', 17), ('showMaps', 10)]], {}), 19: ('wagtail.blocks.ListBlock', (7,), {'default': [], 'help_text': 'Tags automatically applied to every submission.', 'label': 'Mandatory tags'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': content.blocks.districtr_map_slug_choices}), 21: ('wagtail.blocks.ListBlock', (20,), {'default': [], 'help_text': 'Districtr map modules submitters may attach (empty = all).', 'label': 'Allow-listed modules'}), 22: ('wagtail.blocks.StructBlock', [[('mandatoryTags', 19), ('allowListModules', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('name', 3), ('districtr_map_slug', 20)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'default': []}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('simple', 'Simple'), ('megaphone', 'Megaphone')]}), 26: ('wagtail.blocks.StructBlock', [[('views', 24), ('type', 25)]], {})}),
        ),
    ]
