# Generated by Django 5.2.15 on 2026-09-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapi", "0002_provision_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(
                help_text="Stable identifier, minted into members' JWT `teams` claim and stored in portal forms' admin_teams. Changing it permanently orphans those grants — treat as immutable.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
