# Generated by Django 5.2.15 on 2026-08-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0005_grant_admin_team_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
