# Generated by Django 5.2.15 on 2026-08-06 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authapi", "0008_team_slug_and_districtr_maps"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReviewTagAssignment",
        ),
    ]
